
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},m;for(m in g)g.hasOwnProperty(m)&&(aa[m]=g[m]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea=!1,n=!1,fa=!1,ha=!1;ea="object"===typeof window;n="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!n;var p="",ia,ja,ka,la;
if(fa)p=n?require("path").dirname(p)+"/":__dirname+"/",ia=function(a,b){ka||(ka=require("fs"));la||(la=require("path"));a=la.normalize(a);return ka.readFileSync(a,b?null:"utf8")},ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof ma))throw a;}),process.on("unhandledRejection",
r),da=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||n)n?p=self.location.href:"undefined"!==typeof document&&document.currentScript&&(p=document.currentScript.src),p=0!==p.indexOf("blob:")?p.substr(0,p.lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var na=g.print||console.log.bind(console),w=g.printErr||console.warn.bind(console);for(m in aa)aa.hasOwnProperty(m)&&(g[m]=aa[m]);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);function oa(a){pa||(pa={});pa[a]||(pa[a]=1,w(a))}var pa,qa=0,ra;g.wasmBinary&&(ra=g.wasmBinary);var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&r("no native wasm support detected");
function x(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":B[a>>0]=b;break;case "i8":B[a>>0]=b;break;case "i16":sa[a>>1]=b;break;case "i32":C[a>>2]=b;break;case "i64":D=[b>>>0,(E=b,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];C[a>>2]=D[0];C[a+4>>2]=D[1];break;case "float":ta[a>>2]=b;break;case "double":ua[a>>3]=b;break;default:r("invalid type for setValue: "+c)}}var va,wa=!1;
function assert(a,b){a||r("Assertion failed: "+b)}function xa(a,b){b=1==b?ya(a.length):za(a.length);a.subarray||a.slice?F.set(a,b):F.set(new Uint8Array(a),b);return b}var Aa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ba(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Aa)return Aa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function G(a,b){return a?Ba(F,a,b):""}
function Ca(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ea(a){var b=Da(a)+1,c=ya(b);Ca(a,B,c,b);return c}var Fa,B,F,sa,Ga,C,Ha,ta,ua,Ia=g.INITIAL_MEMORY||16777216;g.wasmMemory?va=g.wasmMemory:va=new WebAssembly.Memory({initial:Ia/65536,maximum:Ia/65536});va&&(Fa=va.buffer);Ia=Fa.byteLength;var H=Fa;Fa=H;g.HEAP8=B=new Int8Array(H);g.HEAP16=sa=new Int16Array(H);
g.HEAP32=C=new Int32Array(H);g.HEAPU8=F=new Uint8Array(H);g.HEAPU16=Ga=new Uint16Array(H);g.HEAPU32=Ha=new Uint32Array(H);g.HEAPF32=ta=new Float32Array(H);g.HEAPF64=ua=new Float64Array(H);var I,Ja=[],Ka=[],La=[],Ma=[];function Na(){var a=g.preRun.shift();Ja.unshift(a)}var J=0,Oa=null,Pa=null;g.preloadedImages={};g.preloadedAudios={};function r(a){if(g.onAbort)g.onAbort(a);w(a);wa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Qa(a){var b=L;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ra(){return Qa("data:application/octet-stream;base64,")}var L="index.wasm";if(!Ra()){var Sa=L;L=g.locateFile?g.locateFile(Sa,p):p+Sa}function Ta(){try{if(ra)return new Uint8Array(ra);if(ja)return ja(L);throw"both async and sync fetching of the wasm failed";}catch(a){r(a)}}
function Ua(){return ra||!ea&&!n||"function"!==typeof fetch||Qa("file://")?Promise.resolve().then(Ta):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ta()})}var E,D,Va={2980:function(){window.dispatchEvent(new Event("resize"))}};
function Wa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Qb;"number"===typeof c?void 0===b.kb?I.get(c)():I.get(c)(b.kb):c(void 0===b.kb?null:b.kb)}}}function Xa(a){this.Ua=a-16;this.Cc=function(b){C[this.Ua+8>>2]=b};this.zc=function(b){C[this.Ua+0>>2]=b};this.Ac=function(){C[this.Ua+4>>2]=0};this.yc=function(){B[this.Ua+12>>0]=0};this.Bc=function(){B[this.Ua+13>>0]=0};this.nc=function(b,c){this.Cc(b);this.zc(c);this.Ac();this.yc();this.Bc()}}var Ya=0;
function Za(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function $a(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Za(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function ab(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function bb(a){if("/"===a)return"/";a=$a(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function cb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(fa)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){r("randomDevice")}}
function db(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Za(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var eb=[];function fb(a,b){eb[a]={input:[],output:[],bb:b};gb(a,hb)}
var hb={open:function(a){var b=eb[a.node.rdev];if(!b)throw new M(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.bb.flush(a.tty)},flush:function(a){a.tty.bb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.bb.Rb)throw new M(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.bb.Rb(a.tty)}catch(l){throw new M(29);}if(void 0===h&&0===e)throw new M(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.bb.Gb)throw new M(60);
try{for(var e=0;e<d;e++)a.tty.bb.Gb(a.tty,b[c+e])}catch(f){throw new M(29);}d&&(a.node.timestamp=Date.now());return e}},jb={Rb:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.ic?Buffer.ic(256):new Buffer(256),d=0;try{d=ka.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ib(b,!0)}return a.input.shift()},Gb:function(a,b){null===b||10===b?(na(Ba(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(Ba(a.output,0)),a.output=[])}},kb={Gb:function(a,b){null===b||10===b?(w(Ba(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(w(Ba(a.output,0)),a.output=[])}},N={Wa:null,Ya:function(){return N.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);N.Wa||(N.Wa={dir:{node:{Va:N.Qa.Va,Xa:N.Qa.Xa,lookup:N.Qa.lookup,qb:N.Qa.qb,rename:N.Qa.rename,unlink:N.Qa.unlink,rmdir:N.Qa.rmdir,readdir:N.Qa.readdir,symlink:N.Qa.symlink},stream:{$a:N.Pa.$a}},file:{node:{Va:N.Qa.Va,Xa:N.Qa.Xa},stream:{$a:N.Pa.$a,read:N.Pa.read,write:N.Pa.write,Jb:N.Pa.Jb,rb:N.Pa.rb,ub:N.Pa.ub}},link:{node:{Va:N.Qa.Va,Xa:N.Qa.Xa,readlink:N.Qa.readlink},stream:{}},Lb:{node:{Va:N.Qa.Va,
Xa:N.Qa.Xa},stream:lb}});c=mb(a,b,c,d);16384===(c.mode&61440)?(c.Qa=N.Wa.dir.node,c.Pa=N.Wa.dir.stream,c.Oa={}):32768===(c.mode&61440)?(c.Qa=N.Wa.file.node,c.Pa=N.Wa.file.stream,c.Ra=0,c.Oa=null):40960===(c.mode&61440)?(c.Qa=N.Wa.link.node,c.Pa=N.Wa.link.stream):8192===(c.mode&61440)&&(c.Qa=N.Wa.Lb.node,c.Pa=N.Wa.Lb.stream);c.timestamp=Date.now();a&&(a.Oa[b]=c);return c},Qc:function(a){if(a.Oa&&a.Oa.subarray){for(var b=[],c=0;c<a.Ra;++c)b.push(a.Oa[c]);return b}return a.Oa},Rc:function(a){return a.Oa?
a.Oa.subarray?a.Oa.subarray(0,a.Ra):new Uint8Array(a.Oa):new Uint8Array(0)},Nb:function(a,b){var c=a.Oa?a.Oa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Oa,a.Oa=new Uint8Array(b),0<a.Ra&&a.Oa.set(c.subarray(0,a.Ra),0))},wc:function(a,b){if(a.Ra!=b)if(0==b)a.Oa=null,a.Ra=0;else{if(!a.Oa||a.Oa.subarray){var c=a.Oa;a.Oa=new Uint8Array(b);c&&a.Oa.set(c.subarray(0,Math.min(b,a.Ra)))}else if(a.Oa||(a.Oa=[]),a.Oa.length>b)a.Oa.length=b;else for(;a.Oa.length<b;)a.Oa.push(0);
a.Ra=b}},Qa:{Va:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ra:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.jc=4096;b.blocks=Math.ceil(b.size/b.jc);return b},Xa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&N.wc(a,b.size)},lookup:function(){throw nb[44];},qb:function(a,b,c,d){return N.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=ob(b,c)}catch(f){}if(d)for(var e in d.Oa)throw new M(55);}delete a.parent.Oa[a.name];a.name=c;b.Oa[c]=a;a.parent=b},unlink:function(a,b){delete a.Oa[b]},rmdir:function(a,b){var c=ob(a,b),d;for(d in c.Oa)throw new M(55);delete a.Oa[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Oa)a.Oa.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},Pa:{read:function(a,b,c,d,e){var f=a.node.Oa;if(e>=a.node.Ra)return 0;a=Math.min(a.node.Ra-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Oa||a.Oa.subarray)){if(f)return a.Oa=b.subarray(c,c+d),a.Ra=d;if(0===a.Ra&&0===e)return a.Oa=
b.slice(c,c+d),a.Ra=d;if(e+d<=a.Ra)return a.Oa.set(b.subarray(c,c+d),e),d}N.Nb(a,e+d);if(a.Oa.subarray&&b.subarray)a.Oa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Oa[e+f]=b[c+f];a.Ra=Math.max(a.Ra,e+d);return d},$a:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ra);if(0>b)throw new M(28);return b},Jb:function(a,b,c){N.Nb(a.node,b+c);a.node.Ra=Math.max(a.node.Ra,b+c)},rb:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&61440))throw new M(43);a=a.node.Oa;
if(f&2||a.buffer!==Fa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=za(f);c<f;)B[b+c++]=0;c=b;if(!c)throw new M(48);B.set(a,c)}else d=!1,c=a.byteOffset;return{Ua:c,zb:d}},ub:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(43);if(e&2)return 0;N.Pa.write(a,b,0,d,c,!1);return 0}}},pb=null,qb={},rb=[],sb=1,tb=null,ub=!0,vb={},M=null,nb={};
function O(a,b){a=db("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ob:!0,Hb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Hb)throw new M(32);a=Za(a.split("/").filter(function(h){return!!h}),!1);var e=pb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=ob(e,a[d]);c=$a(c+"/"+a[d]);e.sb&&(!f||f&&b.Ob)&&(e=e.sb.root);if(!f||b.Db)for(f=0;40960===(e.mode&61440);)if(e=wb(c),c=db(ab(c),e),e=O(c,{Hb:b.Hb}).node,40<f++)throw new M(32);}return{path:c,node:e}}
function xb(a){for(var b;;){if(a===a.parent)return a=a.Ya.Wb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function yb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%tb.length}function ob(a,b){var c;if(c=(c=zb(a,"x"))?c:a.Qa.lookup?0:2)throw new M(c,a);for(c=tb[yb(a.id,b)];c;c=c.tc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Qa.lookup(a,b)}
function mb(a,b,c,d){a=new Ab(a,b,c,d);b=yb(a.parent.id,a.name);a.tc=tb[b];return tb[b]=a}var Bb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Cb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function zb(a,b){if(ub)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Db(a,b){try{return ob(a,b),20}catch(c){}return zb(a,"wx")}
function Eb(a){var b=4096;for(a=a||0;a<=b;a++)if(!rb[a])return a;throw new M(33);}function Fb(a,b){Gb||(Gb=function(){},Gb.prototype={});var c=new Gb,d;for(d in a)c[d]=a[d];a=c;b=Eb(b);a.fd=b;return rb[b]=a}var lb={open:function(a){a.Pa=qb[a.node.rdev].Pa;a.Pa.open&&a.Pa.open(a)},$a:function(){throw new M(70);}};function gb(a,b){qb[a]={Pa:b}}
function Hb(a,b){var c="/"===b,d=!b;if(c&&pb)throw new M(10);if(!c&&!d){var e=O(b,{Ob:!1});b=e.path;e=e.node;if(e.sb)throw new M(10);if(16384!==(e.mode&61440))throw new M(54);}b={type:a,$c:{},Wb:b,sc:[]};a=a.Ya(b);a.Ya=b;b.root=a;c?pb=a:e&&(e.sb=b,e.Ya&&e.Ya.sc.push(b))}function Ib(a,b,c){var d=O(a,{parent:!0}).node;a=bb(a);if(!a||"."===a||".."===a)throw new M(28);var e=Db(d,a);if(e)throw new M(e);if(!d.Qa.qb)throw new M(63);return d.Qa.qb(d,a,b,c)}function P(a){Ib(a,16895,0)}
function Jb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Ib(a,b|8192,c)}function Kb(a,b){if(!db(a))throw new M(44);var c=O(b,{parent:!0}).node;if(!c)throw new M(44);b=bb(b);var d=Db(c,b);if(d)throw new M(d);if(!c.Qa.symlink)throw new M(63);c.Qa.symlink(c,b,a)}function wb(a){a=O(a).node;if(!a)throw new M(44);if(!a.Qa.readlink)throw new M(28);return db(xb(a.parent),a.Qa.readlink(a))}
function Lb(a,b,c,d){if(""===a)throw new M(44);if("string"===typeof b){var e=Bb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=$a(a);try{f=O(a,{Db:!(b&131072)}).node}catch(l){}}e=!1;if(b&64)if(f){if(b&128)throw new M(20);}else f=Ib(a,c,0),e=!0;if(!f)throw new M(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new M(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Cb(b)||b&512)?31:zb(f,Cb(b)):44))throw new M(c);if(b&512){c=f;var h;"string"===typeof c?h=O(c,{Db:!0}).node:h=c;if(!h.Qa.Xa)throw new M(63);if(16384===(h.mode&61440))throw new M(31);if(32768!==(h.mode&61440))throw new M(28);if(c=zb(h,"w"))throw new M(c);h.Qa.Xa(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Fb({node:f,path:xb(f),flags:b,seekable:!0,position:0,Pa:f.Pa,Hc:[],error:!1},d);d.Pa.open&&d.Pa.open(d);!g.logReadFiles||b&1||(Mb||(Mb={}),a in Mb||(Mb[a]=1,w("FS.trackingDelegate error on read file: "+
a)));try{vb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),vb.onOpenFile(a,f))}catch(l){w("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function Nb(a){if(null===a.fd)throw new M(8);a.Fb&&(a.Fb=null);try{a.Pa.close&&a.Pa.close(a)}catch(b){throw b;}finally{rb[a.fd]=null}a.fd=null}
function Ob(a,b,c){if(null===a.fd)throw new M(8);if(!a.seekable||!a.Pa.$a)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.Pa.$a(a,b,c);a.Hc=[]}
function Pb(a,b,c,d,e){var f=void 0;if(0>d||0>f)throw new M(28);if(null===a.fd)throw new M(8);if(0===(a.flags&2097155))throw new M(8);if(16384===(a.node.mode&61440))throw new M(31);if(!a.Pa.write)throw new M(28);a.seekable&&a.flags&1024&&Ob(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new M(70);b=a.Pa.write(a,b,c,d,f,e);h||(a.position+=b);try{if(a.path&&vb.onWriteToFile)vb.onWriteToFile(a.path)}catch(l){w("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
l.message)}return b}function Qb(){M||(M=function(a,b){this.node=b;this.xc=function(c){this.Sa=c};this.xc(a);this.message="FS error"},M.prototype=Error(),M.prototype.constructor=M,[44].forEach(function(a){nb[a]=new M(a);nb[a].stack="<generic error, no stack>"}))}var Rb;function Sb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Tb(){var a="/";a="string"===typeof a?a:xb(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=$a(a+"/"+c);try{P(a)}catch(d){}}}}
function Ub(a,b,c){a=$a("/dev/"+a);var d=Sb(!!b,!!c);Vb||(Vb=64);var e=Vb++<<8|0;gb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,l,q){for(var t=0,u=0;u<q;u++){try{var y=b()}catch(z){throw new M(29);}if(void 0===y&&0===t)throw new M(6);if(null===y||void 0===y)break;t++;h[l+u]=y}t&&(f.node.timestamp=Date.now());return t},write:function(f,h,l,q){for(var t=0;t<q;t++)try{c(h[l+t])}catch(u){throw new M(29);}q&&(f.node.timestamp=Date.now());return t}});
Jb(a,d,e)}var Vb,Q={},Gb,Mb,Wb={};
function Xb(a,b){try{var c=O(a,{Db:!0}).node;if(!c)throw new M(44);if(!c.Qa.Va)throw new M(63);var d=c.Qa.Va(c)}catch(e){if(e&&e.node&&$a(a)!==$a(xb(e.node)))return-54;throw e;}C[b>>2]=d.dev;C[b+4>>2]=0;C[b+8>>2]=d.ino;C[b+12>>2]=d.mode;C[b+16>>2]=d.nlink;C[b+20>>2]=d.uid;C[b+24>>2]=d.gid;C[b+28>>2]=d.rdev;C[b+32>>2]=0;D=[d.size>>>0,(E=d.size,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];C[b+40>>2]=D[0];C[b+44>>2]=D[1];C[b+
48>>2]=4096;C[b+52>>2]=d.blocks;C[b+56>>2]=d.atime.getTime()/1E3|0;C[b+60>>2]=0;C[b+64>>2]=d.mtime.getTime()/1E3|0;C[b+68>>2]=0;C[b+72>>2]=d.ctime.getTime()/1E3|0;C[b+76>>2]=0;D=[d.ino>>>0,(E=d.ino,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];C[b+80>>2]=D[0];C[b+84>>2]=D[1];return 0}var Yb=void 0;function Zb(){Yb+=4;return C[Yb-4>>2]}function R(a){a=rb[a];if(!a)throw new M(8);return a}
var S=null,$b=0,ac=null,bc=0,cc=0,dc=0,ec=0,fc=[],hc={},ic,jc,kc,lc=!1,mc=!1,nc=[];
function oc(){function a(){mc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!pc){pc=!0;try{qc=!0}catch(c){qc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}rc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:qc?null:console.log("warning: no BlobBuilder");
sc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Xb||"undefined"!==typeof sc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Xb=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Xb&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(qc)try{h=new Blob([c],{type:tc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:tc(d)}))}catch(t){oa("Blob constructor present but fails: "+
t+"; falling back to blob builder")}h||(h=new rc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=sc.createObjectURL(h),q=new Image;q.onload=function(){assert(q.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=q.width;t.height=q.height;t.getContext("2d").drawImage(q,0,0);g.preloadedImages[d]=t;sc.revokeObjectURL(l);e&&e(c)};q.onerror=function(){console.log("Image "+l+" could not be decoded");f&&f()};q.src=l}});g.preloadPlugins.push({canHandle:function(c){return!g.Zc&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function h(y){q||(q=!0,g.preloadedAudios[d]=y,e&&e(c))}function l(){q||(q=!0,g.preloadedAudios[d]=new Audio,f&&f())}var q=!1;if(qc){try{var t=new Blob([c],{type:tc(d)})}catch(y){return l()}t=sc.createObjectURL(t);var u=new Audio;u.addEventListener("canplaythrough",function(){h(u)},!1);u.onerror=function(){if(!q){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var y="",z=0,k=0,
v=0;v<c.length;v++)for(z=z<<8|c[v],k+=8;6<=k;){var A=z>>k-6&63;k-=6;y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[A]}2==k?(y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(z&3)<<4],y+="=="):4==k&&(y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(z&15)<<2],y+="=");u.src="data:audio/x-"+d.substr(-3)+";base64,"+y;h(u)}};u.src=t;uc(function(){h(u)})}else return l()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!mc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function vc(a,b,c,d){if(b&&g.ab&&a==g.canvas)return g.ab;var e;if(b){var f={antialias:!1,alpha:!1,Tb:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof wc&&(e=xc(a,f)))var l=yc[e].jb}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof T,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.ab=l,b&&(U=yc[e],g.ab=T=U&&U.jb),g.bd=b,nc.forEach(function(q){q()}),oc());return l}
var zc=!1,Ac=void 0,Bc=void 0;
function Cc(a,b){function c(){lc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Dc,Ac&&d.requestPointerLock(),lc=!0,Bc?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=Ha[SDL.screen>>2]|8388608),Ec(g.canvas),Fc()):Ec(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Bc?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=Ha[SDL.screen>>2]&
-8388609),Ec(g.canvas),Fc()):Ec(d));if(g.onFullScreen)g.onFullScreen(lc);if(g.onFullscreen)g.onFullscreen(lc)}Ac=a;Bc=b;"undefined"===typeof Ac&&(Ac=!0);"undefined"===typeof Bc&&(Bc=!1);var d=g.canvas;zc||(zc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Dc(){if(!lc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Gc=0;function Hc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Gc)Gc=b+1E3/60;else for(;b+2>=Gc;)Gc+=1E3/60;setTimeout(a,Math.max(Gc-b,0))}}function uc(a){noExitRuntime=!0;setTimeout(function(){wa||a()},1E4)}
function tc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Ic=0,Jc=0,Kc=0,Lc=0;
function Mc(a){if(mc)"mousemove"!=a.type&&"mozMovementX"in a?Kc=Lc=0:(Kc=a.movementX||a.mozMovementX||a.webkitMovementX||0,Lc=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Ic=SDL.Wc+Kc,Jc=SDL.Xc+Lc):(Ic+=Kc,Jc+=Lc);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,Kc=e-Ic,Lc=a-Jc,Ic=e,Jc=a)}}var Nc=[];function Fc(){var a=g.canvas;Nc.forEach(function(b){b(a.width,a.height)})}function Oc(a,b,c){Ec(g.canvas,a,b);c||Fc()}
function Ec(a,b,c){b&&c?(a.Ic=b,a.mc=c):(b=a.Ic,c=a.mc);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Bc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var pc,qc,rc,sc;
function Pc(a,b){cc=a;dc=b;if(ac)if(0==a)S=function(){var d=Math.max(0,jc+b-Qc())|0;setTimeout(kc,d)};else if(1==a)S=function(){Hc(kc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);n?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}S=function(){setImmediate(kc)}}}var Qc;fa?Qc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Qc=dateNow:Qc=function(){return performance.now()};
function Rc(a,b,c,d,e){noExitRuntime=!0;assert(!ac,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ac=a;bc=d;var f=$b;kc=function(){if(!wa)if(0<fc.length){var h=Date.now(),l=fc.shift();l.Qb(l.kb);if(ic){var q=ic,t=0==q%1?q-1:Math.floor(q);ic=l.Mc?t:(8*q+(t+.5))/9}console.log('main loop blocker "'+l.name+'" took '+(Date.now()-h)+" ms");g.setStatus&&(h=g.statusMessage||
"Please wait...",l=ic,q=hc.Pc,l?l<q?g.setStatus(h+" ("+(q-l)+"/"+q+")"):g.setStatus(h):g.setStatus(""));f<$b||setTimeout(kc,0)}else if(!(f<$b))if(ec=ec+1|0,1==cc&&1<dc&&0!=ec%dc)S();else{0==cc&&(jc=Qc());if(U)for(h=U.eb,U.eb=U.hb,U.hb=h,h=U.Za,U.Za=U.vb,U.vb=h,h=0;21>=h;++h)U.Za[h]=0;a:if(!(wa||g.preMainLoop&&!1===g.preMainLoop())){try{a()}catch(u){if(u instanceof ma||"unwind"==u)break a;u&&"object"===typeof u&&u.stack&&w("exception thrown: "+[u,u.stack]);throw u;}g.postMainLoop&&g.postMainLoop()}f<
$b||("object"===typeof SDL&&SDL.audio&&SDL.audio.vc&&SDL.audio.vc(),S())}};e||(b&&0<b?Pc(0,1E3/b):Pc(1,1),S());if(c)throw"unwind";}var Sc={};function Tc(){if(!Uc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Sc)a[b]=Sc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Uc=c}return Uc}var Uc;
function Vc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Wc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Xc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var Yc=1,Zc=[],$c=[],ad=[],bd=[],cd=[],V=[],dd=[],yc=[],ed=[1,1,2,2,4,4,4,2,3,4,8],fd={},gd={};function hd(a){for(var b=Yc++,c=a.length;c<b;c++)a[c]=null;return b}
function xc(a,b){var c=1<b.Tb?a.getContext("webgl2",b):a.getContext("webgl",b);if(c){a=hd(yc);var d={Sc:a,attributes:b,version:b.Tb,jb:c};c.canvas&&(c.canvas.Jc=d);yc[a]=d;("undefined"===typeof b.lc||b.lc)&&id(d);d.Vb=d.jb.getParameter(34921);d.lb=[];for(b=0;b<d.Vb;b++)d.lb[b]={enabled:!1,Ab:!1,size:0,type:0,Yb:0,Ib:0,Ua:0,ec:null};d.Za=[];d.vb=[];d.Za.length=d.vb.length=22;d.eb=[];d.hb=[];d.eb.length=d.hb.length=22;d.cb=[];d.cb.length=22;for(b=0;21>=b;++b){d.cb[b]=null;d.Za[b]=d.vb[b]=0;d.eb[b]=
[];d.hb[b]=[];c=d.eb[b];var e=d.hb[b];c.length=e.length=64;for(var f=0;64>f;++f)c[f]=e[f]=null}}else a=0;return a}
function id(a){a||(a=U);if(!a.oc){a.oc=!0;var b=a.jb;Vc(b);Wc(b);Xc(b);b.Nc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Vc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.Oc=b.getExtension("EXT_disjoint_timer_query");b.Yc=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var wc={},W,U,jd;function kd(a,b,c,d){for(var e=0;e<a;e++){var f=T[c](),h=f&&hd(d);f?(f.name=h,d[h]=f):W||(W=1282);C[b+4*e>>2]=h}}function ld(a){var b=Da(a)+1,c=za(b);Ca(a,F,c,b);return c}function md(a){a-=5120;return 0==a?B:1==a?F:2==a?sa:4==a?C:6==a?ta:5==a||28922==a||28520==a||30779==a||30782==a?Ha:Ga}
function nd(a,b,c,d,e){a=md(a);var f=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+4-1&-4)>>f)}var od=[];function pd(a,b,c,d){this.id=a;this.y=this.x=0;this.Eb=!1;this.cc=this.bc=0;this.width=b;this.height=c;this.ac=b;this.$b=c;this.title=d;this.attributes=qd;this.buttons=0;this.keys=[];this.Bb=[];this.Kb=this.Sb=this.Cb=this.Zb=this.ob=this.pb=this.tb=this.Pb=this.fc=this.hc=this.title=null}
function rd(a){return 0>=a||!X?null:X[a-1]}var Y=null,X=null,qd=null,td={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function ud(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function vd(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function wd(a){Y&&Y.Kb&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||I.get(Y.Kb)(Y.id,a))}
function xd(a,b){if(Y){var c=ud(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Bb[a]=b;Y.Sb&&(d&&(b=2),I.get(Y.Sb)(Y.id,c,a,b,vd()))}}}function yd(){zd()}function Ad(){zd()}function Bd(a){xd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Cd(a){xd(a.keyCode,0)}function Dd(){if(Y)for(var a=0;a<Y.Bb.length;++a)Y.Bb[a]&&xd(a,0)}function Ed(a){Y&&(Mc(a),a.target==g.canvas&&Y.pb&&I.get(Y.pb)(Y.id,Ic,Jc))}function Fd(a){Y&&a.target==g.canvas&&Y.ob&&I.get(Y.ob)(Y.id,1)}
function Gd(a){Y&&a.target==g.canvas&&Y.ob&&I.get(Y.ob)(Y.id,0)}function Hd(a,b){if(Y&&(Mc(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.tb&&I.get(Y.tb)(Y.id,c,b,vd())}}function Id(a){Y&&Hd(a,1)}function Jd(a){Y&&Hd(a,0)}
function Kd(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Zb&&a.target==g.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;I.get(Y.Zb)(Y.id,b,c);a.preventDefault()}}var Z={},Ld=null,Md=null;
function zd(){if(ec!==Md||!ec){Ld=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;Md=ec;for(var a=0;a<Ld.length;++a){var b=Ld[a];if(b){Z[a]||(console.log("glfw joystick connected:",a),Z[a]={id:xa(ib(b.id),0),Lc:b.buttons.length,Kc:b.axes.length,buttons:xa(Array(b.buttons.length),0),axes:xa(Array(4*b.axes.length),"float")});for(var c=Z[a],d=0;d<b.buttons.length;++d)x(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)x(c.axes+
4*d,b.axes[d],"float")}else Z[a]&&(console.log("glfw joystick disconnected",a),Nd(Z[a].id),Nd(Z[a].buttons),Nd(Z[a].axes),delete Z[a])}}}
function Od(a){function b(l){var q="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=function(y){if(2!=t.readyState)++f,console.log("failed to read dropped file: "+l.name+": "+t.error);else{var z=new Uint8Array(y.target.result);var k=k||{};k.flags=k.flags||577;y=Lb(q,k.flags,k.mode);if("string"===typeof z){var v=new Uint8Array(Da(z)+1);z=Ca(z,v,0,v.length);Pb(y,v,0,z,k.kc)}else if(ArrayBuffer.isView(z))Pb(y,z,0,z.byteLength,k.kc);else throw Error("Unsupported data type");
Nb(y);if(++f===e){I.get(Y.Cb)(Y.id,e,c);for(k=0;k<d.length;++k)Nd(d[k]);Nd(c)}}};t.readAsArrayBuffer(l);var u=xa(ib(q),0);d.push(u);x(c+4*h,u,"i8*")}if(Y&&Y.Cb&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=xa(Array(4*a.dataTransfer.files.length),0),d=[],e=a.dataTransfer.files.length,f=0;Tb();for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}function Pd(a){if(Y&&Y.Cb)return a.preventDefault(),!1}
function Qd(a){return 0===a%4&&(0!==a%100||0===a%400)}function Rd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Sd=[31,29,31,30,31,30,31,31,30,31,30,31],Td=[31,28,31,30,31,30,31,31,30,31,30,31];function Ud(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Qd(a.getFullYear())?Sd:Td)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Vd(a,b,c,d){function e(k,v,A){for(k="number"===typeof k?k.toString():k||"";k.length<v;)k=A[0]+k;return k}function f(k,v){return e(k,v,"0")}function h(k,v){function A(sd){return 0>sd?-1:0<sd?1:0}var K;0===(K=A(k.getFullYear()-v.getFullYear()))&&0===(K=A(k.getMonth()-v.getMonth()))&&(K=A(k.getDate()-v.getDate()));return K}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function q(k){k=Ud(new Date(k.Ta+1900,0,1),k.yb);var v=new Date(k.getFullYear()+1,0,4),A=l(new Date(k.getFullYear(),0,4));v=l(v);return 0>=h(A,k)?0>=h(v,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var t=C[d+40>>2];d={Fc:C[d>>2],Ec:C[d+4>>2],wb:C[d+8>>2],ib:C[d+12>>2],fb:C[d+16>>2],Ta:C[d+20>>2],xb:C[d+24>>2],yb:C[d+28>>2],ad:C[d+32>>2],Dc:C[d+
36>>2],Gc:t?G(t):""};c=G(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in t)c=c.replace(new RegExp(u,"g"),t[u]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
z="January February March April May June July August September October November December".split(" ");t={"%a":function(k){return y[k.xb].substring(0,3)},"%A":function(k){return y[k.xb]},"%b":function(k){return z[k.fb].substring(0,3)},"%B":function(k){return z[k.fb]},"%C":function(k){return f((k.Ta+1900)/100|0,2)},"%d":function(k){return f(k.ib,2)},"%e":function(k){return e(k.ib,2," ")},"%g":function(k){return q(k).toString().substring(2)},"%G":function(k){return q(k)},"%H":function(k){return f(k.wb,
2)},"%I":function(k){k=k.wb;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.ib+Rd(Qd(k.Ta+1900)?Sd:Td,k.fb-1),3)},"%m":function(k){return f(k.fb+1,2)},"%M":function(k){return f(k.Ec,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.wb&&12>k.wb?"AM":"PM"},"%S":function(k){return f(k.Fc,2)},"%t":function(){return"\t"},"%u":function(k){return k.xb||7},"%U":function(k){var v=new Date(k.Ta+1900,0,1),A=0===v.getDay()?v:Ud(v,7-v.getDay());k=new Date(k.Ta+1900,k.fb,k.ib);return 0>
h(A,k)?f(Math.ceil((31-A.getDate()+(Rd(Qd(k.getFullYear())?Sd:Td,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(A,v)?"01":"00"},"%V":function(k){var v=new Date(k.Ta+1901,0,4),A=l(new Date(k.Ta+1900,0,4));v=l(v);var K=Ud(new Date(k.Ta+1900,0,1),k.yb);return 0>h(K,A)?"53":0>=h(v,K)?"01":f(Math.ceil((A.getFullYear()<k.Ta+1900?k.yb+32-A.getDate():k.yb+1-A.getDate())/7),2)},"%w":function(k){return k.xb},"%W":function(k){var v=new Date(k.Ta,0,1),A=1===v.getDay()?v:Ud(v,0===v.getDay()?1:7-v.getDay()+1);k=
new Date(k.Ta+1900,k.fb,k.ib);return 0>h(A,k)?f(Math.ceil((31-A.getDate()+(Rd(Qd(k.getFullYear())?Sd:Td,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(A,v)?"01":"00"},"%y":function(k){return(k.Ta+1900).toString().substring(2)},"%Y":function(k){return k.Ta+1900},"%z":function(k){k=k.Dc;var v=0<=k;k=Math.abs(k)/60;return(v?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Gc},"%%":function(){return"%"}};for(u in t)0<=c.indexOf(u)&&(c=c.replace(new RegExp(u,"g"),t[u](d)));u=
ib(c,!1);if(u.length>b)return 0;B.set(u,a);return u.length-1}var Wd=[];function Ab(a,b,c,d){a||(a=this);this.parent=a;this.Ya=a.Ya;this.sb=null;this.id=sb++;this.name=b;this.mode=c;this.Qa={};this.Pa={};this.rdev=d}Object.defineProperties(Ab.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Qb();tb=Array(4096);Hb(N,"/");P("/tmp");P("/home");
P("/home/web_user");(function(){P("/dev");gb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Jb("/dev/null",259);fb(1280,jb);fb(1536,kb);Jb("/dev/tty",1280);Jb("/dev/tty1",1536);var a=cb();Ub("random",a);Ub("urandom",a);P("/dev/shm");P("/dev/shm/tmp")})();P("/proc");P("/proc/self");P("/proc/self/fd");
Hb({Ya:function(){var a=mb("/proc/self","fd",16895,73);a.Qa={lookup:function(b,c){var d=rb[+c];if(!d)throw new M(8);b={parent:null,Ya:{Wb:"fake"},Qa:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");g.requestFullscreen=function(a,b){Cc(a,b)};g.requestAnimationFrame=function(a){Hc(a)};g.setCanvasSize=function(a,b,c){Oc(a,b,c)};g.pauseMainLoop=function(){S=null;$b++};g.resumeMainLoop=function(){$b++;var a=cc,b=dc,c=ac;ac=null;Rc(c,0,!1,bc,!0);Pc(a,b);S()};
g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return vc(a,b,c,d)};for(var T,Xd=new Float32Array(288),Yd=0;288>Yd;++Yd)od[Yd]=Xd.subarray(0,Yd+1);function ib(a,b){var c=Array(Da(a)+1);a=Ca(a,c,0,c.length);b&&(c.length=a);return c}Ka.push({Qb:function(){Zd()}});
var he={f:function(a){return za(a+16)+16},g:function(a,b,c){(new Xa(a)).nc(b,c);Ya++;throw a;},l:function(a,b,c){Yb=c;try{var d=R(a);switch(b){case 0:var e=Zb();return 0>e?-28:Lb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Zb(),d.flags|=e,0;case 12:return e=Zb(),sa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return C[$d()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof Q&&f instanceof M||r(f),-f.Sa}},R:function(a,b){try{var c=
R(a);return Xb(c.path,b)}catch(d){return"undefined"!==typeof Q&&d instanceof M||r(d),-d.Sa}},O:function(a,b,c){Yb=c;try{var d=R(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Zb();return C[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Zb();if(!d.Pa.pc)throw new M(59);return d.Pa.pc(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:r("bad ioctl syscall "+
b)}}catch(f){return"undefined"!==typeof Q&&f instanceof M||r(f),-f.Sa}},T:function(a,b,c,d,e,f){try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var q=ae(16384,b);if(!q){l=-48;break a}be(q,0,b);h=!0}else{var t=rb[e];if(!t){l=-8;break a}var u=f;if(0!==(c&2)&&0===(d&2)&&2!==(t.flags&2097155))throw new M(2);if(1===(t.flags&2097155))throw new M(2);if(!t.Pa.rb)throw new M(43);var y=t.Pa.rb(t,a,b,u,c,d);q=y.Ua;h=y.zb}Wb[q]={rc:q,qc:b,zb:h,fd:e,uc:c,flags:d,offset:f};l=q}}return l}catch(z){return"undefined"!==
typeof Q&&z instanceof M||r(z),-z.Sa}},S:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=Wb[a];if(d&&b===d.qc){var e=rb[d.fd];if(d.uc&2){var f=d.flags,h=d.offset,l=F.slice(a,a+b);e&&e.Pa.ub&&e.Pa.ub(e,l,h,b,f)}Wb[a]=null;d.zb&&Nd(d.rc)}c=0}return c}catch(q){return"undefined"!==typeof Q&&q instanceof M||r(q),-q.Sa}},r:function(a,b,c){Yb=c;try{var d=G(a),e=Zb();return Lb(d,b,e).fd}catch(f){return"undefined"!==typeof Q&&f instanceof M||r(f),-f.Sa}},Q:function(a,b){try{return a=G(a),Xb(a,
b)}catch(c){return"undefined"!==typeof Q&&c instanceof M||r(c),-c.Sa}},o:function(){r()},ha:function(a,b,c){Wd.length=0;var d;for(c>>=2;d=F[b++];)(d=105>d)&&c&1&&c++,Wd.push(d?ua[c++>>1]:C[c]),++c;return Va[a].apply(null,Wd)},e:function(a,b){ce(a,b||1);throw"longjmp";},J:function(a,b,c){F.copyWithin(a,b,b+c)},d:function(){r("OOM")},ga:function(a,b,c,d,e){Rc(function(){I.get(a)()},b,c,d,e)},M:function(a,b){try{var c=0;Tc().forEach(function(d,e){var f=b+c;e=C[a+4*e>>2]=f;for(f=0;f<d.length;++f)B[e++>>
0]=d.charCodeAt(f);B[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof Q&&d instanceof M||r(d),d.Sa}},N:function(a,b){try{var c=Tc();C[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});C[b>>2]=d;return 0}catch(e){return"undefined"!==typeof Q&&e instanceof M||r(e),e.Sa}},m:function(a){try{var b=R(a);Nb(b);return 0}catch(c){return"undefined"!==typeof Q&&c instanceof M||r(c),c.Sa}},L:function(a,b){try{var c=R(a);B[b>>0]=c.tty?2:16384===(c.mode&61440)?3:40960===(c.mode&61440)?
7:4;return 0}catch(d){return"undefined"!==typeof Q&&d instanceof M||r(d),d.Sa}},q:function(a,b,c,d){try{a:{for(var e=R(a),f=a=0;f<c;f++){var h=C[b+(8*f+4)>>2],l=e,q=C[b+8*f>>2],t=h,u=void 0,y=B;if(0>t||0>u)throw new M(28);if(null===l.fd)throw new M(8);if(1===(l.flags&2097155))throw new M(8);if(16384===(l.node.mode&61440))throw new M(31);if(!l.Pa.read)throw new M(28);var z="undefined"!==typeof u;if(!z)u=l.position;else if(!l.seekable)throw new M(70);var k=l.Pa.read(l,y,q,t,u);z||(l.position+=k);var v=
k;if(0>v){var A=-1;break a}a+=v;if(v<h)break}A=a}C[d>>2]=A;return 0}catch(K){return"undefined"!==typeof Q&&K instanceof M||r(K),K.Sa}},I:function(a,b,c,d,e){try{var f=R(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Ob(f,a,d);D=[f.position>>>0,(E=f.position,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];C[e>>2]=D[0];C[e+4>>2]=D[1];f.Fb&&0===a&&0===d&&(f.Fb=null);return 0}catch(h){return"undefined"!==
typeof Q&&h instanceof M||r(h),h.Sa}},p:function(a,b,c,d){try{a:{for(var e=R(a),f=a=0;f<c;f++){var h=Pb(e,B,C[b+8*f>>2],C[b+(8*f+4)>>2]);if(0>h){var l=-1;break a}a+=h}l=a}C[d>>2]=l;return 0}catch(q){return"undefined"!==typeof Q&&q instanceof M||r(q),q.Sa}},c:function(){return qa|0},t:function(a,b){T.attachShader($c[a],V[b])},k:function(a,b){34962==a?T.mb=b:34963==a&&(T.gb=b);35051==a?T.Mb=b:35052==a&&(T.nb=b);T.bindBuffer(a,Zc[b])},v:function(a,b){T.bindFramebuffer(a,ad[b])},x:function(a,b){T.bindTexture(a,
bd[b])},xa:function(a){T.bindVertexArray(dd[a]);a=T.getParameter(34965);T.gb=a?a.name|0:0},va:function(a){T.blendEquation(a)},ua:function(a,b){T.blendFunc(a,b)},$:function(a,b,c,d,e,f,h,l,q,t){T.blitFramebuffer(a,b,c,d,e,f,h,l,q,t)},A:function(a,b,c,d){2<=U.version?c?T.bufferData(a,F,d,c,b):T.bufferData(a,b,d):T.bufferData(a,c?F.subarray(c,c+b):b,d)},pa:function(a){T.clear(a)},qa:function(a,b,c,d){T.clearColor(a,b,c,d)},y:function(a){T.compileShader(V[a])},aa:function(){var a=hd($c),b=T.createProgram();
b.name=a;$c[a]=b;return a},E:function(a){var b=hd(V);V[b]=T.createShader(a);return b},C:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=Zc[d];e&&(T.deleteBuffer(e),e.name=0,Zc[d]=null,d==T.mb&&(T.mb=0),d==T.gb&&(T.gb=0),d==T.Mb&&(T.Mb=0),d==T.nb&&(T.nb=0))}},_:function(a,b){for(var c=0;c<a;++c){var d=C[b+4*c>>2],e=ad[d];e&&(T.deleteFramebuffer(e),e.name=0,ad[d]=null)}},Y:function(a,b){for(var c=0;c<a;c++){var d=C[b+4*c>>2],e=bd[d];e&&(T.deleteTexture(e),e.name=0,bd[d]=null)}},ta:function(a,
b){for(var c=0;c<a;c++){var d=C[b+4*c>>2];T.deleteVertexArray(dd[d]);dd[d]=null}},D:function(a){T.disable(a)},na:function(a,b,c,d){if(!T.gb){var e=1*ed[c-5120]*b;var f=32-Math.clz32(e-1);var h=U.cb[f];h?f=h:(h=T.getParameter(34965),U.cb[f]=T.createBuffer(),T.bindBuffer(34963,U.cb[f]),T.bufferData(34963,1<<f,35048),T.bindBuffer(34963,h),f=U.cb[f]);T.bindBuffer(34963,f);T.bufferSubData(34963,0,F.subarray(d,d+e));d=0}jd=!1;for(e=0;e<U.Vb;++e)if(f=U.lb[e],f.Ab&&f.enabled){jd=!0;h=f.Ib;h=0<h?b*h:f.size*
ed[f.type-5120]*b;var l=32-Math.clz32(h-1);var q=U.eb[l],t=U.Za[l];U.Za[l]=U.Za[l]+1&63;var u=q[t];u?l=u:(u=T.getParameter(34964),q[t]=T.createBuffer(),T.bindBuffer(34962,q[t]),T.bufferData(34962,1<<l,35048),T.bindBuffer(34962,u),l=q[t]);T.bindBuffer(34962,l);T.bufferSubData(34962,0,F.subarray(f.Ua,f.Ua+h));f.ec.call(T,e,f.size,f.type,f.Yb,f.Ib,0)}T.drawElements(a,b,c,d);jd&&T.bindBuffer(34962,Zc[T.mb]);T.gb||T.bindBuffer(34963,null)},wa:function(a){T.enable(a)},i:function(a){U.lb[a].enabled=!0;T.enableVertexAttribArray(a)},
u:function(a,b,c,d,e){T.framebufferTexture2D(a,b,c,bd[d],e)},F:function(a,b){kd(a,b,"createBuffer",Zc)},ba:function(a,b){kd(a,b,"createFramebuffer",ad)},da:function(a,b){kd(a,b,"createTexture",bd)},ya:function(a,b){kd(a,b,"createVertexArray",dd)},j:function(a,b){return T.getAttribLocation($c[a],G(b))},Ba:function(a,b,c,d){a=T.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?Ca(a,F,d,b):0;c&&(C[c>>2]=b)},G:function(a,b,c){c?35716==b?(a=T.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),
C[c>>2]=a?a.length+1:0):35720==b?(a=T.getShaderSource(V[a]),C[c>>2]=a?a.length+1:0):C[c>>2]=T.getShaderParameter(V[a],b):W||(W=1281)},z:function(a){if(gd[a])return gd[a];switch(a){case 7939:var b=T.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=ld(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=T.getParameter(a))||W||(W=1280);b=ld(b);break;case 7938:b=T.getParameter(7938);b=2<=U.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=ld(b);break;case 35724:b=
T.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=ld(b);break;default:return W||(W=1280),0}return gd[a]=b},H:function(a,b){b=G(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=fd[a]&&fd[a].dc[b])&&0<=c&&c<a[0]?a[1]+c:-1},P:function(a){T.linkProgram($c[a]);var b=$c[a];a=fd[a]={dc:{},Ub:0,Tc:-1,Uc:-1};for(var c=a.dc,
d=T.getProgramParameter(b,35718),e=0;e<d;++e){var f=T.getActiveUniform(b,e),h=f.name;a.Ub=Math.max(a.Ub,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var l=T.getUniformLocation(b,h);if(l){var q=hd(cd);c[h]=[f.size,q];cd[q]=l;for(var t=1;t<f.size;++t)l=T.getUniformLocation(b,h+"["+t+"]"),q=hd(cd),cd[q]=l}}},B:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?C[d+4*f>>2]:-1;e+=G(C[c+4*f>>2],0>h?void 0:h)}T.shaderSource(V[a],e)},ca:function(a,b,c,d,e,f,h,l,q){if(2<=U.version)if(T.nb)T.texImage2D(a,
b,c,d,e,f,h,l,q);else if(q){var t=md(l);T.texImage2D(a,b,c,d,e,f,h,l,t,q>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else T.texImage2D(a,b,c,d,e,f,h,l,null);else T.texImage2D(a,b,c,d,e,f,h,l,q?nd(l,h,d,e,q):null)},w:function(a,b,c){T.texParameteri(a,b,c)},Z:function(a,b,c,d,e,f,h,l,q){if(2<=U.version)if(T.nb)T.texSubImage2D(a,b,c,d,e,f,h,l,q);else if(q){var t=md(l);T.texSubImage2D(a,b,c,d,e,f,h,l,t,q>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else T.texSubImage2D(a,b,c,d,e,f,h,l,null);else t=null,q&&(t=nd(l,h,
e,f,q)),T.texSubImage2D(a,b,c,d,e,f,h,l,t)},oa:function(a,b,c,d){if(2<=U.version)T.uniformMatrix4fv(cd[a],!!c,ta,d>>2,16*b);else{if(18>=b){var e=od[16*b-1],f=ta;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3];e[h+4]=f[l+4];e[h+5]=f[l+5];e[h+6]=f[l+6];e[h+7]=f[l+7];e[h+8]=f[l+8];e[h+9]=f[l+9];e[h+10]=f[l+10];e[h+11]=f[l+11];e[h+12]=f[l+12];e[h+13]=f[l+13];e[h+14]=f[l+14];e[h+15]=f[l+15]}}else e=ta.subarray(d>>2,d+64*b>>2);T.uniformMatrix4fv(cd[a],!!c,e)}},
n:function(a){T.useProgram($c[a])},h:function(a,b,c,d,e,f){var h=U.lb[a];T.mb?(h.Ab=!1,T.vertexAttribPointer(a,b,c,!!d,e,f)):(h.size=b,h.type=c,h.Yb=d,h.Ib=e,h.Ua=f,h.Ab=!0,h.ec=function(l,q,t,u,y,z){this.vertexAttribPointer(l,q,t,u,y,z)})},ra:function(a,b,c,d){T.viewport(a,b,c,d)},ja:function(a,b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?Cc():Oc(a,b);for(e=0;e<X.length&&null==X[e];e++);
e==X.length&&(g.ab=vc(g.canvas,!0,!0,{antialias:1<qd[135181],depth:0<qd[135173],stencil:0<qd[135174],alpha:0<qd[135172]}));g.ab?(a=new pd(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,Y=a,f=a.id):f=0}return f},fa:function(a){a:{if(a=rd(a)){a.fc&&I.get(a.fc)(a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}g.ab=void 0}a=void 0}return a},X:function(a,b,c){x(b,Ic,"double");x(c,Jc,"double")},sa:function(a,b,c){var d=0,e=0;if(a=rd(a))d=a.width,e=a.height;b&&
x(b,d,"i32");c&&x(c,e,"i32")},ka:function(){if(X)return 1;Qc();qd=td;X=[];Y=null;window.addEventListener("gamepadconnected",yd,!0);window.addEventListener("gamepaddisconnected",Ad,!0);window.addEventListener("keydown",Bd,!0);window.addEventListener("keypress",wd,!0);window.addEventListener("keyup",Cd,!0);window.addEventListener("blur",Dd,!0);g.canvas.addEventListener("touchmove",Ed,!0);g.canvas.addEventListener("touchstart",Id,!0);g.canvas.addEventListener("touchcancel",Jd,!0);g.canvas.addEventListener("touchend",
Jd,!0);g.canvas.addEventListener("mousemove",Ed,!0);g.canvas.addEventListener("mousedown",Id,!0);g.canvas.addEventListener("mouseup",Jd,!0);g.canvas.addEventListener("wheel",Kd,!0);g.canvas.addEventListener("mousewheel",Kd,!0);g.canvas.addEventListener("mouseenter",Fd,!0);g.canvas.addEventListener("mouseleave",Gd,!0);g.canvas.addEventListener("drop",Od,!0);g.canvas.addEventListener("dragover",Pd,!0);Nc.push(function(a,b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||
document.webkitIsFullScreen?(Y.bc=Y.x,Y.cc=Y.y,Y.ac=Y.width,Y.$b=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Eb=!0):1==Y.Eb?(Y.x=Y.bc,Y.y=Y.cc,Y.width=Y.ac,Y.height=Y.$b,Y.Eb=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(Oc(Y.width,Y.height,!0),Y&&Y.hc&&I.get(Y.hc)(Y.id,Y.width,Y.height),Y&&Y.Pb&&I.get(Y.Pb)(Y.id,Y.width,Y.height))}});return 1},ia:function(){},la:function(){},Aa:function(a,b){if(a=rd(a)){var c=a.pb;a.pb=b;b=c}else b=null;return b},za:function(a,
b){if(a=rd(a)){var c=a.tb;a.tb=b;b=c}else b=null;return b},ma:function(){},ea:function(){window.removeEventListener("gamepadconnected",yd,!0);window.removeEventListener("gamepaddisconnected",Ad,!0);window.removeEventListener("keydown",Bd,!0);window.removeEventListener("keypress",wd,!0);window.removeEventListener("keyup",Cd,!0);window.removeEventListener("blur",Dd,!0);g.canvas.removeEventListener("touchmove",Ed,!0);g.canvas.removeEventListener("touchstart",Id,!0);g.canvas.removeEventListener("touchcancel",
Jd,!0);g.canvas.removeEventListener("touchend",Jd,!0);g.canvas.removeEventListener("mousemove",Ed,!0);g.canvas.removeEventListener("mousedown",Id,!0);g.canvas.removeEventListener("mouseup",Jd,!0);g.canvas.removeEventListener("wheel",Kd,!0);g.canvas.removeEventListener("mousewheel",Kd,!0);g.canvas.removeEventListener("mouseenter",Fd,!0);g.canvas.removeEventListener("mouseleave",Gd,!0);g.canvas.removeEventListener("drop",Od,!0);g.canvas.removeEventListener("dragover",Pd,!0);g.canvas.width=g.canvas.height=
1;Y=X=null},W:de,s:ee,V:fe,U:ge,a:va,b:function(a){qa=a|0},K:function(a,b,c,d){return Vd(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;I=g.asm.Ca;J--;g.monitorRunDependencies&&g.monitorRunDependencies(J);0==J&&(null!==Oa&&(clearInterval(Oa),Oa=null),Pa&&(e=Pa,Pa=null,e()))}function b(e){a(e.instance)}function c(e){return Ua().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){w("failed to asynchronously prepare wasm: "+f);r(f)})}var d={a:he};J++;g.monitorRunDependencies&&g.monitorRunDependencies(J);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return w("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return ra||"function"!==typeof WebAssembly.instantiateStreaming||Ra()||Qa("file://")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){w("wasm streaming compile failed: "+f);w("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Zd=g.___wasm_call_ctors=function(){return(Zd=g.___wasm_call_ctors=g.asm.Da).apply(null,arguments)};
g._main=function(){return(g._main=g.asm.Ea).apply(null,arguments)};
var za=g._malloc=function(){return(za=g._malloc=g.asm.Fa).apply(null,arguments)},be=g._memset=function(){return(be=g._memset=g.asm.Ga).apply(null,arguments)},Nd=g._free=function(){return(Nd=g._free=g.asm.Ha).apply(null,arguments)},$d=g.___errno_location=function(){return($d=g.___errno_location=g.asm.Ia).apply(null,arguments)},ie=g.stackSave=function(){return(ie=g.stackSave=g.asm.Ja).apply(null,arguments)},je=g.stackRestore=function(){return(je=g.stackRestore=g.asm.Ka).apply(null,arguments)},ya=g.stackAlloc=
function(){return(ya=g.stackAlloc=g.asm.La).apply(null,arguments)},ce=g._setThrew=function(){return(ce=g._setThrew=g.asm.Ma).apply(null,arguments)},ae=g._memalign=function(){return(ae=g._memalign=g.asm.Na).apply(null,arguments)};function de(a,b,c){var d=ie();try{return I.get(a)(b,c)}catch(e){je(d);if(e!==e+0&&"longjmp"!==e)throw e;ce(1,0)}}function fe(a,b,c,d,e){var f=ie();try{return I.get(a)(b,c,d,e)}catch(h){je(f);if(h!==h+0&&"longjmp"!==h)throw h;ce(1,0)}}
function ee(a,b,c,d){var e=ie();try{return I.get(a)(b,c,d)}catch(f){je(e);if(f!==f+0&&"longjmp"!==f)throw f;ce(1,0)}}function ge(a,b,c){var d=ie();try{I.get(a)(b,c)}catch(e){je(d);if(e!==e+0&&"longjmp"!==e)throw e;ce(1,0)}}var ke;function ma(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Pa=function le(){ke||me();ke||(Pa=le)};
function me(a){function b(){if(!ke&&(ke=!0,g.calledRun=!0,!wa)){g.noFSInit||Rb||(Rb=!0,Qb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Ub("stdin",g.stdin):Kb("/dev/tty","/dev/stdin"),g.stdout?Ub("stdout",null,g.stdout):Kb("/dev/tty","/dev/stdout"),g.stderr?Ub("stderr",null,g.stderr):Kb("/dev/tty1","/dev/stderr"),Lb("/dev/stdin",0),Lb("/dev/stdout",1),Lb("/dev/stderr",1));Wa(Ka);ub=!1;Wa(La);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(ne){var c=a,d=g._main;c=c||[];var e=
c.length+1,f=ya(4*(e+1));C[f>>2]=Ea(ca);for(var h=1;h<e;h++)C[(f>>2)+h]=Ea(c[h-1]);C[(f>>2)+e]=0;try{var l=d(e,f);if(!noExitRuntime||0!==l){if(!noExitRuntime){if(g.onExit)g.onExit(l);wa=!0}da(l,new ma(l))}}catch(q){q instanceof ma||("unwind"==q?noExitRuntime=!0:((c=q)&&"object"===typeof q&&q.stack&&(c=[q,q.stack]),w("exception thrown: "+c),da(1,q)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Ma.unshift(c);Wa(Ma)}}a=a||ba;
if(!(0<J)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Na();Wa(Ja);0<J||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=me;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var ne=!0;g.noInitialRun&&(ne=!1);noExitRuntime=!0;me();
