
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},m;for(m in g)g.hasOwnProperty(m)&&(aa[m]=g[m]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea=!1,n=!1,fa=!1,ha=!1;ea="object"===typeof window;n="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!n;var p="",ia,ja,ka,la;
if(fa)p=n?require("path").dirname(p)+"/":__dirname+"/",ia=function(a,b){ka||(ka=require("fs"));la||(la=require("path"));a=la.normalize(a);return ka.readFileSync(a,b?null:"utf8")},ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof ma))throw a;}),process.on("unhandledRejection",
r),da=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||n)n?p=self.location.href:"undefined"!==typeof document&&document.currentScript&&(p=document.currentScript.src),p=0!==p.indexOf("blob:")?p.substr(0,p.lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var na=g.print||console.log.bind(console),w=g.printErr||console.warn.bind(console);for(m in aa)aa.hasOwnProperty(m)&&(g[m]=aa[m]);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);function oa(a){pa||(pa={});pa[a]||(pa[a]=1,w(a))}var pa,qa=0,ra;g.wasmBinary&&(ra=g.wasmBinary);var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&r("no native wasm support detected");
function sa(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":x[a>>0]=b;break;case "i8":x[a>>0]=b;break;case "i16":ta[a>>1]=b;break;case "i32":A[a>>2]=b;break;case "i64":C=[b>>>0,(D=b,1<=+Math.abs(D)?0<D?(Math.min(+Math.floor(D/4294967296),4294967295)|0)>>>0:~~+Math.ceil((D-+(~~D>>>0))/4294967296)>>>0:0)];A[a>>2]=C[0];A[a+4>>2]=C[1];break;case "float":ua[a>>2]=b;break;case "double":va[a>>3]=b;break;default:r("invalid type for setValue: "+c)}}var wa,xa=!1;
function assert(a,b){a||r("Assertion failed: "+b)}function ya(a,b){b=1==b?za(a.length):Aa(a.length);a.subarray||a.slice?E.set(a,b):E.set(new Uint8Array(a),b);return b}var Ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ca(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ba)return Ba.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function F(a,b){return a?Ca(E,a,b):""}
function Da(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Fa(a){var b=Ea(a)+1,c=za(b);Da(a,x,c,b);return c}var Ga,x,E,ta,Ha,A,Ia,ua,va,Ja=g.INITIAL_MEMORY||16777216;g.wasmMemory?wa=g.wasmMemory:wa=new WebAssembly.Memory({initial:Ja/65536,maximum:Ja/65536});wa&&(Ga=wa.buffer);Ja=Ga.byteLength;var G=Ga;Ga=G;g.HEAP8=x=new Int8Array(G);g.HEAP16=ta=new Int16Array(G);
g.HEAP32=A=new Int32Array(G);g.HEAPU8=E=new Uint8Array(G);g.HEAPU16=Ha=new Uint16Array(G);g.HEAPU32=Ia=new Uint32Array(G);g.HEAPF32=ua=new Float32Array(G);g.HEAPF64=va=new Float64Array(G);var H,Ka=[],La=[],Ma=[],Na=[];function Oa(){var a=g.preRun.shift();Ka.unshift(a)}var I=0,Pa=null,Qa=null;g.preloadedImages={};g.preloadedAudios={};function r(a){if(g.onAbort)g.onAbort(a);w(a);xa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Ra(a){var b=J;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Sa(){return Ra("data:application/octet-stream;base64,")}var J="index.wasm";if(!Sa()){var Ta=J;J=g.locateFile?g.locateFile(Ta,p):p+Ta}function Ua(){try{if(ra)return new Uint8Array(ra);if(ja)return ja(J);throw"both async and sync fetching of the wasm failed";}catch(a){r(a)}}
function Va(){return ra||!ea&&!n||"function"!==typeof fetch||Ra("file://")?Promise.resolve().then(Ua):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ua()})}var D,C,Wa={2884:function(){window.dispatchEvent(new Event("resize"))}};
function Xa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Pb;"number"===typeof c?void 0===b.kb?H.get(c)():H.get(c)(b.kb):c(void 0===b.kb?null:b.kb)}}}function Ya(a){this.Ua=a-16;this.Cc=function(b){A[this.Ua+8>>2]=b};this.zc=function(b){A[this.Ua+0>>2]=b};this.Ac=function(){A[this.Ua+4>>2]=0};this.yc=function(){x[this.Ua+12>>0]=0};this.Bc=function(){x[this.Ua+13>>0]=0};this.nc=function(b,c){this.Cc(b);this.zc(c);this.Ac();this.yc();this.Bc()}}var Za=0;
function $a(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function ab(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=$a(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function bb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function cb(a){if("/"===a)return"/";a=ab(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function db(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(fa)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){r("randomDevice")}}
function eb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=$a(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var fb=[];function gb(a,b){fb[a]={input:[],output:[],bb:b};hb(a,ib)}
var ib={open:function(a){var b=fb[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.bb.flush(a.tty)},flush:function(a){a.tty.bb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.bb.Qb)throw new L(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.bb.Qb(a.tty)}catch(l){throw new L(29);}if(void 0===h&&0===e)throw new L(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.bb.Eb)throw new L(60);
try{for(var e=0;e<d;e++)a.tty.bb.Eb(a.tty,b[c+e])}catch(f){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},kb={Qb:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.ic?Buffer.ic(256):new Buffer(256),d=0;try{d=ka.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=jb(b,!0)}return a.input.shift()},Eb:function(a,b){null===b||10===b?(na(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(Ca(a.output,0)),a.output=[])}},lb={Eb:function(a,b){null===b||10===b?(w(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(w(Ca(a.output,0)),a.output=[])}},M={Wa:null,Ya:function(){return M.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.Wa||(M.Wa={dir:{node:{Va:M.Qa.Va,Xa:M.Qa.Xa,lookup:M.Qa.lookup,pb:M.Qa.pb,rename:M.Qa.rename,unlink:M.Qa.unlink,rmdir:M.Qa.rmdir,readdir:M.Qa.readdir,symlink:M.Qa.symlink},stream:{$a:M.Pa.$a}},file:{node:{Va:M.Qa.Va,Xa:M.Qa.Xa},stream:{$a:M.Pa.$a,read:M.Pa.read,write:M.Pa.write,Hb:M.Pa.Hb,qb:M.Pa.qb,sb:M.Pa.sb}},link:{node:{Va:M.Qa.Va,Xa:M.Qa.Xa,readlink:M.Qa.readlink},stream:{}},Jb:{node:{Va:M.Qa.Va,
Xa:M.Qa.Xa},stream:mb}});c=nb(a,b,c,d);16384===(c.mode&61440)?(c.Qa=M.Wa.dir.node,c.Pa=M.Wa.dir.stream,c.Oa={}):32768===(c.mode&61440)?(c.Qa=M.Wa.file.node,c.Pa=M.Wa.file.stream,c.Ra=0,c.Oa=null):40960===(c.mode&61440)?(c.Qa=M.Wa.link.node,c.Pa=M.Wa.link.stream):8192===(c.mode&61440)&&(c.Qa=M.Wa.Jb.node,c.Pa=M.Wa.Jb.stream);c.timestamp=Date.now();a&&(a.Oa[b]=c);return c},Qc:function(a){if(a.Oa&&a.Oa.subarray){for(var b=[],c=0;c<a.Ra;++c)b.push(a.Oa[c]);return b}return a.Oa},Rc:function(a){return a.Oa?
a.Oa.subarray?a.Oa.subarray(0,a.Ra):new Uint8Array(a.Oa):new Uint8Array(0)},Mb:function(a,b){var c=a.Oa?a.Oa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Oa,a.Oa=new Uint8Array(b),0<a.Ra&&a.Oa.set(c.subarray(0,a.Ra),0))},wc:function(a,b){if(a.Ra!=b)if(0==b)a.Oa=null,a.Ra=0;else{if(!a.Oa||a.Oa.subarray){var c=a.Oa;a.Oa=new Uint8Array(b);c&&a.Oa.set(c.subarray(0,Math.min(b,a.Ra)))}else if(a.Oa||(a.Oa=[]),a.Oa.length>b)a.Oa.length=b;else for(;a.Oa.length<b;)a.Oa.push(0);
a.Ra=b}},Qa:{Va:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ra:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.jc=4096;b.blocks=Math.ceil(b.size/b.jc);return b},Xa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&M.wc(a,b.size)},lookup:function(){throw ob[44];},pb:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=pb(b,c)}catch(f){}if(d)for(var e in d.Oa)throw new L(55);}delete a.parent.Oa[a.name];a.name=c;b.Oa[c]=a;a.parent=b},unlink:function(a,b){delete a.Oa[b]},rmdir:function(a,b){var c=pb(a,b),d;for(d in c.Oa)throw new L(55);delete a.Oa[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Oa)a.Oa.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},Pa:{read:function(a,b,c,d,e){var f=a.node.Oa;if(e>=a.node.Ra)return 0;a=Math.min(a.node.Ra-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Oa||a.Oa.subarray)){if(f)return a.Oa=b.subarray(c,c+d),a.Ra=d;if(0===a.Ra&&0===e)return a.Oa=
b.slice(c,c+d),a.Ra=d;if(e+d<=a.Ra)return a.Oa.set(b.subarray(c,c+d),e),d}M.Mb(a,e+d);if(a.Oa.subarray&&b.subarray)a.Oa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Oa[e+f]=b[c+f];a.Ra=Math.max(a.Ra,e+d);return d},$a:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ra);if(0>b)throw new L(28);return b},Hb:function(a,b,c){M.Mb(a.node,b+c);a.node.Ra=Math.max(a.node.Ra,b+c)},qb:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.Oa;
if(f&2||a.buffer!==Ga){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=Aa(f);c<f;)x[b+c++]=0;c=b;if(!c)throw new L(48);x.set(a,c)}else d=!1,c=a.byteOffset;return{Ua:c,xb:d}},sb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.Pa.write(a,b,0,d,c,!1);return 0}}},qb=null,rb={},sb=[],tb=1,ub=null,vb=!0,wb={},L=null,ob={};
function N(a,b){a=eb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Nb:!0,Fb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Fb)throw new L(32);a=$a(a.split("/").filter(function(h){return!!h}),!1);var e=qb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=pb(e,a[d]);c=ab(c+"/"+a[d]);e.rb&&(!f||f&&b.Nb)&&(e=e.rb.root);if(!f||b.Bb)for(f=0;40960===(e.mode&61440);)if(e=xb(c),c=eb(bb(c),e),e=N(c,{Fb:b.Fb}).node,40<f++)throw new L(32);}return{path:c,node:e}}
function yb(a){for(var b;;){if(a===a.parent)return a=a.Ya.Vb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ub.length}function pb(a,b){var c;if(c=(c=Ab(a,"x"))?c:a.Qa.lookup?0:2)throw new L(c,a);for(c=ub[zb(a.id,b)];c;c=c.tc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Qa.lookup(a,b)}
function nb(a,b,c,d){a=new Bb(a,b,c,d);b=zb(a.parent.id,a.name);a.tc=ub[b];return ub[b]=a}var Cb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Db(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ab(a,b){if(vb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Eb(a,b){try{return pb(a,b),20}catch(c){}return Ab(a,"wx")}
function Fb(a){var b=4096;for(a=a||0;a<=b;a++)if(!sb[a])return a;throw new L(33);}function Gb(a,b){Hb||(Hb=function(){},Hb.prototype={});var c=new Hb,d;for(d in a)c[d]=a[d];a=c;b=Fb(b);a.fd=b;return sb[b]=a}var mb={open:function(a){a.Pa=rb[a.node.rdev].Pa;a.Pa.open&&a.Pa.open(a)},$a:function(){throw new L(70);}};function hb(a,b){rb[a]={Pa:b}}
function Ib(a,b){var c="/"===b,d=!b;if(c&&qb)throw new L(10);if(!c&&!d){var e=N(b,{Nb:!1});b=e.path;e=e.node;if(e.rb)throw new L(10);if(16384!==(e.mode&61440))throw new L(54);}b={type:a,$c:{},Vb:b,sc:[]};a=a.Ya(b);a.Ya=b;b.root=a;c?qb=a:e&&(e.rb=b,e.Ya&&e.Ya.sc.push(b))}function Jb(a,b,c){var d=N(a,{parent:!0}).node;a=cb(a);if(!a||"."===a||".."===a)throw new L(28);var e=Eb(d,a);if(e)throw new L(e);if(!d.Qa.pb)throw new L(63);return d.Qa.pb(d,a,b,c)}function O(a){Jb(a,16895,0)}
function Kb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Jb(a,b|8192,c)}function Lb(a,b){if(!eb(a))throw new L(44);var c=N(b,{parent:!0}).node;if(!c)throw new L(44);b=cb(b);var d=Eb(c,b);if(d)throw new L(d);if(!c.Qa.symlink)throw new L(63);c.Qa.symlink(c,b,a)}function xb(a){a=N(a).node;if(!a)throw new L(44);if(!a.Qa.readlink)throw new L(28);return eb(yb(a.parent),a.Qa.readlink(a))}
function Mb(a,b,c,d){if(""===a)throw new L(44);if("string"===typeof b){var e=Cb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=ab(a);try{f=N(a,{Bb:!(b&131072)}).node}catch(l){}}e=!1;if(b&64)if(f){if(b&128)throw new L(20);}else f=Jb(a,c,0),e=!0;if(!f)throw new L(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new L(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Db(b)||b&512)?31:Ab(f,Db(b)):44))throw new L(c);if(b&512){c=f;var h;"string"===typeof c?h=N(c,{Bb:!0}).node:h=c;if(!h.Qa.Xa)throw new L(63);if(16384===(h.mode&61440))throw new L(31);if(32768!==(h.mode&61440))throw new L(28);if(c=Ab(h,"w"))throw new L(c);h.Qa.Xa(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Gb({node:f,path:yb(f),flags:b,seekable:!0,position:0,Pa:f.Pa,Hc:[],error:!1},d);d.Pa.open&&d.Pa.open(d);!g.logReadFiles||b&1||(Nb||(Nb={}),a in Nb||(Nb[a]=1,w("FS.trackingDelegate error on read file: "+
a)));try{wb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),wb.onOpenFile(a,f))}catch(l){w("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function Ob(a){if(null===a.fd)throw new L(8);a.Db&&(a.Db=null);try{a.Pa.close&&a.Pa.close(a)}catch(b){throw b;}finally{sb[a.fd]=null}a.fd=null}
function Pb(a,b,c){if(null===a.fd)throw new L(8);if(!a.seekable||!a.Pa.$a)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.Pa.$a(a,b,c);a.Hc=[]}
function Qb(a,b,c,d,e){var f=void 0;if(0>d||0>f)throw new L(28);if(null===a.fd)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(16384===(a.node.mode&61440))throw new L(31);if(!a.Pa.write)throw new L(28);a.seekable&&a.flags&1024&&Pb(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new L(70);b=a.Pa.write(a,b,c,d,f,e);h||(a.position+=b);try{if(a.path&&wb.onWriteToFile)wb.onWriteToFile(a.path)}catch(l){w("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
l.message)}return b}function Rb(){L||(L=function(a,b){this.node=b;this.xc=function(c){this.Sa=c};this.xc(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){ob[a]=new L(a);ob[a].stack="<generic error, no stack>"}))}var Sb;function Tb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Ub(){var a="/";a="string"===typeof a?a:yb(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=ab(a+"/"+c);try{O(a)}catch(d){}}}}
function Vb(a,b,c){a=ab("/dev/"+a);var d=Tb(!!b,!!c);Wb||(Wb=64);var e=Wb++<<8|0;hb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,l,q){for(var t=0,u=0;u<q;u++){try{var y=b()}catch(z){throw new L(29);}if(void 0===y&&0===t)throw new L(6);if(null===y||void 0===y)break;t++;h[l+u]=y}t&&(f.node.timestamp=Date.now());return t},write:function(f,h,l,q){for(var t=0;t<q;t++)try{c(h[l+t])}catch(u){throw new L(29);}q&&(f.node.timestamp=Date.now());return t}});
Kb(a,d,e)}var Wb,P={},Hb,Nb,Xb={};
function Yb(a,b){try{var c=N(a,{Bb:!0}).node;if(!c)throw new L(44);if(!c.Qa.Va)throw new L(63);var d=c.Qa.Va(c)}catch(e){if(e&&e.node&&ab(a)!==ab(yb(e.node)))return-54;throw e;}A[b>>2]=d.dev;A[b+4>>2]=0;A[b+8>>2]=d.ino;A[b+12>>2]=d.mode;A[b+16>>2]=d.nlink;A[b+20>>2]=d.uid;A[b+24>>2]=d.gid;A[b+28>>2]=d.rdev;A[b+32>>2]=0;C=[d.size>>>0,(D=d.size,1<=+Math.abs(D)?0<D?(Math.min(+Math.floor(D/4294967296),4294967295)|0)>>>0:~~+Math.ceil((D-+(~~D>>>0))/4294967296)>>>0:0)];A[b+40>>2]=C[0];A[b+44>>2]=C[1];A[b+
48>>2]=4096;A[b+52>>2]=d.blocks;A[b+56>>2]=d.atime.getTime()/1E3|0;A[b+60>>2]=0;A[b+64>>2]=d.mtime.getTime()/1E3|0;A[b+68>>2]=0;A[b+72>>2]=d.ctime.getTime()/1E3|0;A[b+76>>2]=0;C=[d.ino>>>0,(D=d.ino,1<=+Math.abs(D)?0<D?(Math.min(+Math.floor(D/4294967296),4294967295)|0)>>>0:~~+Math.ceil((D-+(~~D>>>0))/4294967296)>>>0:0)];A[b+80>>2]=C[0];A[b+84>>2]=C[1];return 0}var Zb=void 0;function $b(){Zb+=4;return A[Zb-4>>2]}function Q(a){a=sb[a];if(!a)throw new L(8);return a}
var R=null,ac=0,bc=null,cc=0,dc=0,ec=0,fc=0,hc=[],ic={},jc,kc,lc,mc=!1,nc=!1,oc=[];
function pc(){function a(){nc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!qc){qc=!0;try{rc=!0}catch(c){rc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}sc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:rc?null:console.log("warning: no BlobBuilder");
tc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Xb||"undefined"!==typeof tc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Xb=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Xb&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var h=null;if(rc)try{h=new Blob([c],{type:uc(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:uc(d)}))}catch(t){oa("Blob constructor present but fails: "+
t+"; falling back to blob builder")}h||(h=new sc,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=tc.createObjectURL(h),q=new Image;q.onload=function(){assert(q.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=q.width;t.height=q.height;t.getContext("2d").drawImage(q,0,0);g.preloadedImages[d]=t;tc.revokeObjectURL(l);e&&e(c)};q.onerror=function(){console.log("Image "+l+" could not be decoded");f&&f()};q.src=l}});g.preloadPlugins.push({canHandle:function(c){return!g.Zc&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function h(y){q||(q=!0,g.preloadedAudios[d]=y,e&&e(c))}function l(){q||(q=!0,g.preloadedAudios[d]=new Audio,f&&f())}var q=!1;if(rc){try{var t=new Blob([c],{type:uc(d)})}catch(y){return l()}t=tc.createObjectURL(t);var u=new Audio;u.addEventListener("canplaythrough",function(){h(u)},!1);u.onerror=function(){if(!q){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var y="",z=0,k=0,
v=0;v<c.length;v++)for(z=z<<8|c[v],k+=8;6<=k;){var B=z>>k-6&63;k-=6;y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[B]}2==k?(y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(z&3)<<4],y+="=="):4==k&&(y+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(z&15)<<2],y+="=");u.src="data:audio/x-"+d.substr(-3)+";base64,"+y;h(u)}};u.src=t;vc(function(){h(u)})}else return l()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!nc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function wc(a,b,c,d){if(b&&g.ab&&a==g.canvas)return g.ab;var e;if(b){var f={antialias:!1,alpha:!1,Sb:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var h in d)f[h]=d[h];if("undefined"!==typeof xc&&(e=yc(a,f)))var l=zc[e].jb}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof S,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.ab=l,b&&(T=zc[e],g.ab=S=T&&T.jb),g.bd=b,oc.forEach(function(q){q()}),pc());return l}
var Ac=!1,Bc=void 0,Cc=void 0;
function Dc(a,b){function c(){mc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Ec,Bc&&d.requestPointerLock(),mc=!0,Cc?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=Ia[SDL.screen>>2]|8388608),Fc(g.canvas),Gc()):Fc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Cc?("undefined"!=typeof SDL&&(A[SDL.screen>>2]=Ia[SDL.screen>>2]&
-8388609),Fc(g.canvas),Gc()):Fc(d));if(g.onFullScreen)g.onFullScreen(mc);if(g.onFullscreen)g.onFullscreen(mc)}Bc=a;Cc=b;"undefined"===typeof Bc&&(Bc=!0);"undefined"===typeof Cc&&(Cc=!1);var d=g.canvas;Ac||(Ac=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Ec(){if(!mc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Hc=0;function Ic(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Hc)Hc=b+1E3/60;else for(;b+2>=Hc;)Hc+=1E3/60;setTimeout(a,Math.max(Hc-b,0))}}function vc(a){noExitRuntime=!0;setTimeout(function(){xa||a()},1E4)}
function uc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Jc=0,Kc=0,Lc=0,Mc=0;
function Nc(a){if(nc)"mousemove"!=a.type&&"mozMovementX"in a?Lc=Mc=0:(Lc=a.movementX||a.mozMovementX||a.webkitMovementX||0,Mc=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Jc=SDL.Wc+Lc,Kc=SDL.Xc+Mc):(Jc+=Lc,Kc+=Mc);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,Lc=e-Jc,Mc=a-Kc,Jc=e,Kc=a)}}var Oc=[];function Gc(){var a=g.canvas;Oc.forEach(function(b){b(a.width,a.height)})}function Pc(a,b,c){Fc(g.canvas,a,b);c||Gc()}
function Fc(a,b,c){b&&c?(a.Ic=b,a.mc=c):(b=a.Ic,c=a.mc);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Cc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var qc,rc,sc,tc;
function Qc(a,b){dc=a;ec=b;if(bc)if(0==a)R=function(){var d=Math.max(0,kc+b-Rc())|0;setTimeout(lc,d)};else if(1==a)R=function(){Ic(lc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);n?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}R=function(){setImmediate(lc)}}}var Rc;fa?Rc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Rc=dateNow:Rc=function(){return performance.now()};
function Sc(a,b,c,d,e){noExitRuntime=!0;assert(!bc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");bc=a;cc=d;var f=ac;lc=function(){if(!xa)if(0<hc.length){var h=Date.now(),l=hc.shift();l.Pb(l.kb);if(jc){var q=jc,t=0==q%1?q-1:Math.floor(q);jc=l.Mc?t:(8*q+(t+.5))/9}console.log('main loop blocker "'+l.name+'" took '+(Date.now()-h)+" ms");g.setStatus&&(h=g.statusMessage||
"Please wait...",l=jc,q=ic.Pc,l?l<q?g.setStatus(h+" ("+(q-l)+"/"+q+")"):g.setStatus(h):g.setStatus(""));f<ac||setTimeout(lc,0)}else if(!(f<ac))if(fc=fc+1|0,1==dc&&1<ec&&0!=fc%ec)R();else{0==dc&&(kc=Rc());if(T)for(h=T.eb,T.eb=T.hb,T.hb=h,h=T.Za,T.Za=T.tb,T.tb=h,h=0;21>=h;++h)T.Za[h]=0;a:if(!(xa||g.preMainLoop&&!1===g.preMainLoop())){try{a()}catch(u){if(u instanceof ma||"unwind"==u)break a;u&&"object"===typeof u&&u.stack&&w("exception thrown: "+[u,u.stack]);throw u;}g.postMainLoop&&g.postMainLoop()}f<
ac||("object"===typeof SDL&&SDL.audio&&SDL.audio.vc&&SDL.audio.vc(),R())}};e||(b&&0<b?Qc(0,1E3/b):Qc(1,1),R());if(c)throw"unwind";}var Tc={};function Uc(){if(!Vc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Tc)a[b]=Tc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Vc=c}return Vc}var Vc;
function Wc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Xc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Yc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var Zc=1,$c=[],ad=[],bd=[],cd=[],dd=[],U=[],ed=[],zc=[],fd=[1,1,2,2,4,4,4,2,3,4,8],gd={},hd={};function id(a){for(var b=Zc++,c=a.length;c<b;c++)a[c]=null;return b}
function yc(a,b){var c=1<b.Sb?a.getContext("webgl2",b):a.getContext("webgl",b);if(c){a=id(zc);var d={Sc:a,attributes:b,version:b.Sb,jb:c};c.canvas&&(c.canvas.Jc=d);zc[a]=d;("undefined"===typeof b.lc||b.lc)&&jd(d);d.Ub=d.jb.getParameter(34921);d.lb=[];for(b=0;b<d.Ub;b++)d.lb[b]={enabled:!1,yb:!1,size:0,type:0,Yb:0,Gb:0,Ua:0,ec:null};d.Za=[];d.tb=[];d.Za.length=d.tb.length=22;d.eb=[];d.hb=[];d.eb.length=d.hb.length=22;d.cb=[];d.cb.length=22;for(b=0;21>=b;++b){d.cb[b]=null;d.Za[b]=d.tb[b]=0;d.eb[b]=
[];d.hb[b]=[];c=d.eb[b];var e=d.hb[b];c.length=e.length=64;for(var f=0;64>f;++f)c[f]=e[f]=null}}else a=0;return a}
function jd(a){a||(a=T);if(!a.oc){a.oc=!0;var b=a.jb;Wc(b);Xc(b);Yc(b);b.Nc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Vc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.Oc=b.getExtension("EXT_disjoint_timer_query");b.Yc=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var xc={},V,T,kd;function ld(a,b,c,d){for(var e=0;e<a;e++){var f=S[c](),h=f&&id(d);f?(f.name=h,d[h]=f):V||(V=1282);A[b+4*e>>2]=h}}function md(a){var b=Ea(a)+1,c=Aa(b);Da(a,E,c,b);return c}function nd(a){a-=5120;return 0==a?x:1==a?E:2==a?ta:4==a?A:6==a?ua:5==a||28922==a||28520==a||30779==a||30782==a?Ia:Ha}
function od(a,b,c,d,e){a=nd(a);var f=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+4-1&-4)>>f)}var pd=[];function qd(a,b,c,d){this.id=a;this.y=this.x=0;this.Cb=!1;this.cc=this.bc=0;this.width=b;this.height=c;this.ac=b;this.$b=c;this.title=d;this.attributes=sd;this.buttons=0;this.keys=[];this.zb=[];this.Ib=this.Rb=this.Ab=this.Zb=this.ob=this.Lb=this.Wb=this.Ob=this.fc=this.hc=this.title=null}
var W=null,X=null,sd=null,td={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function ud(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function vd(){var a=W,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function wd(a){W&&W.Ib&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||H.get(W.Ib)(W.id,a))}
function xd(a,b){if(W){var c=ud(a);if(-1!=c){var d=b&&W.keys[c];W.keys[c]=b;W.zb[a]=b;W.Rb&&(d&&(b=2),H.get(W.Rb)(W.id,c,a,b,vd()))}}}function yd(){zd()}function Ad(){zd()}function Bd(a){xd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Cd(a){xd(a.keyCode,0)}function Dd(){if(W)for(var a=0;a<W.zb.length;++a)W.zb[a]&&xd(a,0)}function Ed(a){W&&(Nc(a),a.target==g.canvas&&W.Lb&&H.get(W.Lb)(W.id,Jc,Kc))}function Fd(a){W&&a.target==g.canvas&&W.ob&&H.get(W.ob)(W.id,1)}
function Gd(a){W&&a.target==g.canvas&&W.ob&&H.get(W.ob)(W.id,0)}function Hd(a,b){if(W&&(Nc(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){W.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else W.buttons&=~(1<<c);W.Wb&&H.get(W.Wb)(W.id,c,b,vd())}}function Id(a){W&&Hd(a,1)}function Jd(a){W&&Hd(a,0)}
function Kd(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(W&&W.Zb&&a.target==g.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;H.get(W.Zb)(W.id,b,c);a.preventDefault()}}var Y={},Ld=null,Md=null;
function zd(){if(fc!==Md||!fc){Ld=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;Md=fc;for(var a=0;a<Ld.length;++a){var b=Ld[a];if(b){Y[a]||(console.log("glfw joystick connected:",a),Y[a]={id:ya(jb(b.id),0),Lc:b.buttons.length,Kc:b.axes.length,buttons:ya(Array(b.buttons.length),0),axes:ya(Array(4*b.axes.length),"float")});for(var c=Y[a],d=0;d<b.buttons.length;++d)sa(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)sa(c.axes+
4*d,b.axes[d],"float")}else Y[a]&&(console.log("glfw joystick disconnected",a),Nd(Y[a].id),Nd(Y[a].buttons),Nd(Y[a].axes),delete Y[a])}}}
function Od(a){function b(l){var q="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=function(y){if(2!=t.readyState)++f,console.log("failed to read dropped file: "+l.name+": "+t.error);else{var z=new Uint8Array(y.target.result);var k=k||{};k.flags=k.flags||577;y=Mb(q,k.flags,k.mode);if("string"===typeof z){var v=new Uint8Array(Ea(z)+1);z=Da(z,v,0,v.length);Qb(y,v,0,z,k.kc)}else if(ArrayBuffer.isView(z))Qb(y,z,0,z.byteLength,k.kc);else throw Error("Unsupported data type");
Ob(y);if(++f===e){H.get(W.Ab)(W.id,e,c);for(k=0;k<d.length;++k)Nd(d[k]);Nd(c)}}};t.readAsArrayBuffer(l);var u=ya(jb(q),0);d.push(u);sa(c+4*h,u,"i8*")}if(W&&W.Ab&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=ya(Array(4*a.dataTransfer.files.length),0),d=[],e=a.dataTransfer.files.length,f=0;Ub();for(var h=0;h<e;++h)b(a.dataTransfer.files[h]);return!1}}function Pd(a){if(W&&W.Ab)return a.preventDefault(),!1}
function Qd(a){return 0===a%4&&(0!==a%100||0===a%400)}function Rd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Sd=[31,29,31,30,31,30,31,31,30,31,30,31],Td=[31,28,31,30,31,30,31,31,30,31,30,31];function Ud(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Qd(a.getFullYear())?Sd:Td)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Vd(a,b,c,d){function e(k,v,B){for(k="number"===typeof k?k.toString():k||"";k.length<v;)k=B[0]+k;return k}function f(k,v){return e(k,v,"0")}function h(k,v){function B(rd){return 0>rd?-1:0<rd?1:0}var K;0===(K=B(k.getFullYear()-v.getFullYear()))&&0===(K=B(k.getMonth()-v.getMonth()))&&(K=B(k.getDate()-v.getDate()));return K}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function q(k){k=Ud(new Date(k.Ta+1900,0,1),k.wb);var v=new Date(k.getFullYear()+1,0,4),B=l(new Date(k.getFullYear(),0,4));v=l(v);return 0>=h(B,k)?0>=h(v,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var t=A[d+40>>2];d={Fc:A[d>>2],Ec:A[d+4>>2],ub:A[d+8>>2],ib:A[d+12>>2],fb:A[d+16>>2],Ta:A[d+20>>2],vb:A[d+24>>2],wb:A[d+28>>2],ad:A[d+32>>2],Dc:A[d+
36>>2],Gc:t?F(t):""};c=F(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in t)c=c.replace(new RegExp(u,"g"),t[u]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
z="January February March April May June July August September October November December".split(" ");t={"%a":function(k){return y[k.vb].substring(0,3)},"%A":function(k){return y[k.vb]},"%b":function(k){return z[k.fb].substring(0,3)},"%B":function(k){return z[k.fb]},"%C":function(k){return f((k.Ta+1900)/100|0,2)},"%d":function(k){return f(k.ib,2)},"%e":function(k){return e(k.ib,2," ")},"%g":function(k){return q(k).toString().substring(2)},"%G":function(k){return q(k)},"%H":function(k){return f(k.ub,
2)},"%I":function(k){k=k.ub;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.ib+Rd(Qd(k.Ta+1900)?Sd:Td,k.fb-1),3)},"%m":function(k){return f(k.fb+1,2)},"%M":function(k){return f(k.Ec,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.ub&&12>k.ub?"AM":"PM"},"%S":function(k){return f(k.Fc,2)},"%t":function(){return"\t"},"%u":function(k){return k.vb||7},"%U":function(k){var v=new Date(k.Ta+1900,0,1),B=0===v.getDay()?v:Ud(v,7-v.getDay());k=new Date(k.Ta+1900,k.fb,k.ib);return 0>
h(B,k)?f(Math.ceil((31-B.getDate()+(Rd(Qd(k.getFullYear())?Sd:Td,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(B,v)?"01":"00"},"%V":function(k){var v=new Date(k.Ta+1901,0,4),B=l(new Date(k.Ta+1900,0,4));v=l(v);var K=Ud(new Date(k.Ta+1900,0,1),k.wb);return 0>h(K,B)?"53":0>=h(v,K)?"01":f(Math.ceil((B.getFullYear()<k.Ta+1900?k.wb+32-B.getDate():k.wb+1-B.getDate())/7),2)},"%w":function(k){return k.vb},"%W":function(k){var v=new Date(k.Ta,0,1),B=1===v.getDay()?v:Ud(v,0===v.getDay()?1:7-v.getDay()+1);k=
new Date(k.Ta+1900,k.fb,k.ib);return 0>h(B,k)?f(Math.ceil((31-B.getDate()+(Rd(Qd(k.getFullYear())?Sd:Td,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(B,v)?"01":"00"},"%y":function(k){return(k.Ta+1900).toString().substring(2)},"%Y":function(k){return k.Ta+1900},"%z":function(k){k=k.Dc;var v=0<=k;k=Math.abs(k)/60;return(v?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Gc},"%%":function(){return"%"}};for(u in t)0<=c.indexOf(u)&&(c=c.replace(new RegExp(u,"g"),t[u](d)));u=
jb(c,!1);if(u.length>b)return 0;x.set(u,a);return u.length-1}var Wd=[];function Bb(a,b,c,d){a||(a=this);this.parent=a;this.Ya=a.Ya;this.rb=null;this.id=tb++;this.name=b;this.mode=c;this.Qa={};this.Pa={};this.rdev=d}Object.defineProperties(Bb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Rb();ub=Array(4096);Ib(M,"/");O("/tmp");O("/home");
O("/home/web_user");(function(){O("/dev");hb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Kb("/dev/null",259);gb(1280,kb);gb(1536,lb);Kb("/dev/tty",1280);Kb("/dev/tty1",1536);var a=db();Vb("random",a);Vb("urandom",a);O("/dev/shm");O("/dev/shm/tmp")})();O("/proc");O("/proc/self");O("/proc/self/fd");
Ib({Ya:function(){var a=nb("/proc/self","fd",16895,73);a.Qa={lookup:function(b,c){var d=sb[+c];if(!d)throw new L(8);b={parent:null,Ya:{Vb:"fake"},Qa:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");g.requestFullscreen=function(a,b){Dc(a,b)};g.requestAnimationFrame=function(a){Ic(a)};g.setCanvasSize=function(a,b,c){Pc(a,b,c)};g.pauseMainLoop=function(){R=null;ac++};g.resumeMainLoop=function(){ac++;var a=dc,b=ec,c=bc;bc=null;Sc(c,0,!1,cc,!0);Qc(a,b);R()};
g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return wc(a,b,c,d)};for(var S,Xd=new Float32Array(288),Yd=0;288>Yd;++Yd)pd[Yd]=Xd.subarray(0,Yd+1);function jb(a,b){var c=Array(Ea(a)+1);a=Da(a,c,0,c.length);b&&(c.length=a);return c}La.push({Pb:function(){Zd()}});
var ie={b:function(a,b,c,d){r("Assertion failed: "+F(a)+", at: "+[b?F(b):"unknown filename",c,d?F(d):"unknown function"])},f:function(a){return Aa(a+16)+16},m:function(a,b,c){(new Ya(a)).nc(b,c);Za++;throw a;},l:function(a,b,c){Zb=c;try{var d=Q(a);switch(b){case 0:var e=$b();return 0>e?-28:Mb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=$b(),d.flags|=e,0;case 12:return e=$b(),ta[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return A[$d()>>
2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof P&&f instanceof L||r(f),-f.Sa}},U:function(a,b){try{var c=Q(a);return Yb(c.path,b)}catch(d){return"undefined"!==typeof P&&d instanceof L||r(d),-d.Sa}},P:function(a,b,c){Zb=c;try{var d=Q(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=$b();return A[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=$b();if(!d.Pa.pc)throw new L(59);
return d.Pa.pc(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:r("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof P&&f instanceof L||r(f),-f.Sa}},Q:function(a,b,c,d,e,f){try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var q=ae(16384,b);if(!q){l=-48;break a}be(q,0,b);h=!0}else{var t=sb[e];if(!t){l=-8;break a}var u=f;if(0!==(c&2)&&0===(d&2)&&2!==(t.flags&2097155))throw new L(2);if(1===(t.flags&2097155))throw new L(2);if(!t.Pa.qb)throw new L(43);
var y=t.Pa.qb(t,a,b,u,c,d);q=y.Ua;h=y.xb}Xb[q]={rc:q,qc:b,xb:h,fd:e,uc:c,flags:d,offset:f};l=q}}return l}catch(z){return"undefined"!==typeof P&&z instanceof L||r(z),-z.Sa}},S:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=Xb[a];if(d&&b===d.qc){var e=sb[d.fd];if(d.uc&2){var f=d.flags,h=d.offset,l=E.slice(a,a+b);e&&e.Pa.sb&&e.Pa.sb(e,l,h,b,f)}Xb[a]=null;d.xb&&Nd(d.rc)}c=0}return c}catch(q){return"undefined"!==typeof P&&q instanceof L||r(q),-q.Sa}},r:function(a,b,c){Zb=c;try{var d=F(a),
e=$b();return Mb(d,b,e).fd}catch(f){return"undefined"!==typeof P&&f instanceof L||r(f),-f.Sa}},T:function(a,b){try{return a=F(a),Yb(a,b)}catch(c){return"undefined"!==typeof P&&c instanceof L||r(c),-c.Sa}},o:function(){r()},ja:function(a,b,c){Wd.length=0;var d;for(c>>=2;d=E[b++];)(d=105>d)&&c&1&&c++,Wd.push(d?va[c++>>1]:A[c]),++c;return Wa[a].apply(null,Wd)},e:function(a,b){Z(a,b||1);throw"longjmp";},J:function(a,b,c){E.copyWithin(a,b,b+c)},K:function(){r("OOM")},ia:function(a,b,c,d,e){Sc(function(){H.get(a)()},
b,c,d,e)},N:function(a,b){try{var c=0;Uc().forEach(function(d,e){var f=b+c;e=A[a+4*e>>2]=f;for(f=0;f<d.length;++f)x[e++>>0]=d.charCodeAt(f);x[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof P&&d instanceof L||r(d),d.Sa}},O:function(a,b){try{var c=Uc();A[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A[b>>2]=d;return 0}catch(e){return"undefined"!==typeof P&&e instanceof L||r(e),e.Sa}},k:function(a){try{var b=Q(a);Ob(b);return 0}catch(c){return"undefined"!==typeof P&&
c instanceof L||r(c),c.Sa}},M:function(a,b){try{var c=Q(a);x[b>>0]=c.tty?2:16384===(c.mode&61440)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof P&&d instanceof L||r(d),d.Sa}},q:function(a,b,c,d){try{a:{for(var e=Q(a),f=a=0;f<c;f++){var h=A[b+(8*f+4)>>2],l=e,q=A[b+8*f>>2],t=h,u=void 0,y=x;if(0>t||0>u)throw new L(28);if(null===l.fd)throw new L(8);if(1===(l.flags&2097155))throw new L(8);if(16384===(l.node.mode&61440))throw new L(31);if(!l.Pa.read)throw new L(28);var z="undefined"!==
typeof u;if(!z)u=l.position;else if(!l.seekable)throw new L(70);var k=l.Pa.read(l,y,q,t,u);z||(l.position+=k);var v=k;if(0>v){var B=-1;break a}a+=v;if(v<h)break}B=a}A[d>>2]=B;return 0}catch(K){return"undefined"!==typeof P&&K instanceof L||r(K),K.Sa}},I:function(a,b,c,d,e){try{var f=Q(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Pb(f,a,d);C=[f.position>>>0,(D=f.position,1<=+Math.abs(D)?0<D?(Math.min(+Math.floor(D/4294967296),4294967295)|0)>>>0:~~+Math.ceil((D-+(~~D>>>
0))/4294967296)>>>0:0)];A[e>>2]=C[0];A[e+4>>2]=C[1];f.Db&&0===a&&0===d&&(f.Db=null);return 0}catch(h){return"undefined"!==typeof P&&h instanceof L||r(h),h.Sa}},p:function(a,b,c,d){try{a:{for(var e=Q(a),f=a=0;f<c;f++){var h=Qb(e,x,A[b+8*f>>2],A[b+(8*f+4)>>2]);if(0>h){var l=-1;break a}a+=h}l=a}A[d>>2]=l;return 0}catch(q){return"undefined"!==typeof P&&q instanceof L||r(q),q.Sa}},c:function(){return qa|0},t:function(a,b){S.attachShader(ad[a],U[b])},j:function(a,b){34962==a?S.mb=b:34963==a&&(S.gb=b);35051==
a?S.Kb=b:35052==a&&(S.nb=b);S.bindBuffer(a,$c[b])},v:function(a,b){S.bindFramebuffer(a,bd[b])},x:function(a,b){S.bindTexture(a,cd[b])},za:function(a){S.bindVertexArray(ed[a]);a=S.getParameter(34965);S.gb=a?a.name|0:0},xa:function(a){S.blendEquation(a)},wa:function(a,b){S.blendFunc(a,b)},ca:function(a,b,c,d,e,f,h,l,q,t){S.blitFramebuffer(a,b,c,d,e,f,h,l,q,t)},B:function(a,b,c,d){2<=T.version?c?S.bufferData(a,E,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?E.subarray(c,c+b):b,d)},ra:function(a){S.clear(a)},
sa:function(a,b,c,d){S.clearColor(a,b,c,d)},y:function(a){S.compileShader(U[a])},ba:function(){var a=id(ad),b=S.createProgram();b.name=a;ad[a]=b;return a},E:function(a){var b=id(U);U[b]=S.createShader(a);return b},C:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=$c[d];e&&(S.deleteBuffer(e),e.name=0,$c[d]=null,d==S.mb&&(S.mb=0),d==S.gb&&(S.gb=0),d==S.Kb&&(S.Kb=0),d==S.nb&&(S.nb=0))}},aa:function(a,b){for(var c=0;c<a;++c){var d=A[b+4*c>>2],e=bd[d];e&&(S.deleteFramebuffer(e),e.name=0,bd[d]=null)}},
_:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2],e=cd[d];e&&(S.deleteTexture(e),e.name=0,cd[d]=null)}},va:function(a,b){for(var c=0;c<a;c++){var d=A[b+4*c>>2];S.deleteVertexArray(ed[d]);ed[d]=null}},D:function(a){S.disable(a)},pa:function(a,b,c,d){if(!S.gb){var e=1*fd[c-5120]*b;var f=32-Math.clz32(e-1);var h=T.cb[f];h?f=h:(h=S.getParameter(34965),T.cb[f]=S.createBuffer(),S.bindBuffer(34963,T.cb[f]),S.bufferData(34963,1<<f,35048),S.bindBuffer(34963,h),f=T.cb[f]);S.bindBuffer(34963,f);S.bufferSubData(34963,
0,E.subarray(d,d+e));d=0}kd=!1;for(e=0;e<T.Ub;++e)if(f=T.lb[e],f.yb&&f.enabled){kd=!0;h=f.Gb;h=0<h?b*h:f.size*fd[f.type-5120]*b;var l=32-Math.clz32(h-1);var q=T.eb[l],t=T.Za[l];T.Za[l]=T.Za[l]+1&63;var u=q[t];u?l=u:(u=S.getParameter(34964),q[t]=S.createBuffer(),S.bindBuffer(34962,q[t]),S.bufferData(34962,1<<l,35048),S.bindBuffer(34962,u),l=q[t]);S.bindBuffer(34962,l);S.bufferSubData(34962,0,E.subarray(f.Ua,f.Ua+h));f.ec.call(S,e,f.size,f.type,f.Yb,f.Gb,0)}S.drawElements(a,b,c,d);kd&&S.bindBuffer(34962,
$c[S.mb]);S.gb||S.bindBuffer(34963,null)},ya:function(a){S.enable(a)},h:function(a){T.lb[a].enabled=!0;S.enableVertexAttribArray(a)},u:function(a,b,c,d,e){S.framebufferTexture2D(a,b,c,cd[d],e)},F:function(a,b){ld(a,b,"createBuffer",$c)},da:function(a,b){ld(a,b,"createFramebuffer",bd)},fa:function(a,b){ld(a,b,"createTexture",cd)},Aa:function(a,b){ld(a,b,"createVertexArray",ed)},i:function(a,b){return S.getAttribLocation(ad[a],F(b))},Ba:function(a,b,c,d){a=S.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");
b=0<b&&d?Da(a,E,d,b):0;c&&(A[c>>2]=b)},G:function(a,b,c){c?35716==b?(a=S.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),A[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(U[a]),A[c>>2]=a?a.length+1:0):A[c>>2]=S.getShaderParameter(U[a],b):V||(V=1281)},z:function(a){if(hd[a])return hd[a];switch(a){case 7939:var b=S.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=md(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=S.getParameter(a))||V||(V=1280);
b=md(b);break;case 7938:b=S.getParameter(7938);b=2<=T.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=md(b);break;case 35724:b=S.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=md(b);break;default:return V||(V=1280),0}return hd[a]=b},H:function(a,b){b=F(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=
gd[a]&&gd[a].dc[b])&&0<=c&&c<a[0]?a[1]+c:-1},R:function(a){S.linkProgram(ad[a]);var b=ad[a];a=gd[a]={dc:{},Tb:0,Tc:-1,Uc:-1};for(var c=a.dc,d=S.getProgramParameter(b,35718),e=0;e<d;++e){var f=S.getActiveUniform(b,e),h=f.name;a.Tb=Math.max(a.Tb,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var l=S.getUniformLocation(b,h);if(l){var q=id(dd);c[h]=[f.size,q];dd[q]=l;for(var t=1;t<f.size;++t)l=S.getUniformLocation(b,h+"["+t+"]"),q=id(dd),dd[q]=l}}},A:function(a,b,c,d){for(var e="",f=
0;f<b;++f){var h=d?A[d+4*f>>2]:-1;e+=F(A[c+4*f>>2],0>h?void 0:h)}S.shaderSource(U[a],e)},ea:function(a,b,c,d,e,f,h,l,q){if(2<=T.version)if(S.nb)S.texImage2D(a,b,c,d,e,f,h,l,q);else if(q){var t=nd(l);S.texImage2D(a,b,c,d,e,f,h,l,t,q>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else S.texImage2D(a,b,c,d,e,f,h,l,null);else S.texImage2D(a,b,c,d,e,f,h,l,q?od(l,h,d,e,q):null)},w:function(a,b,c){S.texParameteri(a,b,c)},$:function(a,b,c,d,e,f,h,l,q){if(2<=T.version)if(S.nb)S.texSubImage2D(a,b,c,d,e,f,h,l,q);else if(q){var t=
nd(l);S.texSubImage2D(a,b,c,d,e,f,h,l,t,q>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else S.texSubImage2D(a,b,c,d,e,f,h,l,null);else t=null,q&&(t=od(l,h,e,f,q)),S.texSubImage2D(a,b,c,d,e,f,h,l,t)},qa:function(a,b,c,d){if(2<=T.version)S.uniformMatrix4fv(dd[a],!!c,ua,d>>2,16*b);else{if(18>=b){var e=pd[16*b-1],f=ua;d>>=2;for(var h=0;h<16*b;h+=16){var l=d+h;e[h]=f[l];e[h+1]=f[l+1];e[h+2]=f[l+2];e[h+3]=f[l+3];e[h+4]=f[l+4];e[h+5]=f[l+5];e[h+6]=f[l+6];e[h+7]=f[l+7];e[h+8]=f[l+8];e[h+9]=f[l+9];e[h+10]=f[l+10];
e[h+11]=f[l+11];e[h+12]=f[l+12];e[h+13]=f[l+13];e[h+14]=f[l+14];e[h+15]=f[l+15]}}else e=ua.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(dd[a],!!c,e)}},n:function(a){S.useProgram(ad[a])},g:function(a,b,c,d,e,f){var h=T.lb[a];S.mb?(h.yb=!1,S.vertexAttribPointer(a,b,c,!!d,e,f)):(h.size=b,h.type=c,h.Yb=d,h.Gb=e,h.Ua=f,h.yb=!0,h.ec=function(l,q,t,u,y,z){this.vertexAttribPointer(l,q,t,u,y,z)})},ta:function(a,b,c,d){S.viewport(a,b,c,d)},la:function(a,b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<
e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||0>=b)f=0;else{d?Dc():Pc(a,b);for(e=0;e<X.length&&null==X[e];e++);e==X.length&&(g.ab=wc(g.canvas,!0,!0,{antialias:1<sd[135181],depth:0<sd[135173],stencil:0<sd[135174],alpha:0<sd[135172]}));g.ab?(a=new qd(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,W=a,f=a.id):f=0}return f},ha:function(a){a:{if(a=0>=a||!X?null:X[a-1]){a.fc&&H.get(a.fc)(a.id);X[a.id-1]=null;W.id==a.id&&(W=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=
void 0;break a}g.ab=void 0}a=void 0}return a},ua:function(a,b,c){var d=0,e=0;if(a=0>=a||!X?null:X[a-1])d=a.width,e=a.height;b&&sa(b,d,"i32");c&&sa(c,e,"i32")},ma:function(){if(X)return 1;Rc();sd=td;X=[];W=null;window.addEventListener("gamepadconnected",yd,!0);window.addEventListener("gamepaddisconnected",Ad,!0);window.addEventListener("keydown",Bd,!0);window.addEventListener("keypress",wd,!0);window.addEventListener("keyup",Cd,!0);window.addEventListener("blur",Dd,!0);g.canvas.addEventListener("touchmove",
Ed,!0);g.canvas.addEventListener("touchstart",Id,!0);g.canvas.addEventListener("touchcancel",Jd,!0);g.canvas.addEventListener("touchend",Jd,!0);g.canvas.addEventListener("mousemove",Ed,!0);g.canvas.addEventListener("mousedown",Id,!0);g.canvas.addEventListener("mouseup",Jd,!0);g.canvas.addEventListener("wheel",Kd,!0);g.canvas.addEventListener("mousewheel",Kd,!0);g.canvas.addEventListener("mouseenter",Fd,!0);g.canvas.addEventListener("mouseleave",Gd,!0);g.canvas.addEventListener("drop",Od,!0);g.canvas.addEventListener("dragover",
Pd,!0);Oc.push(function(a,b){if(W){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(W.bc=W.x,W.cc=W.y,W.ac=W.width,W.$b=W.height,W.x=W.y=0,W.width=screen.width,W.height=screen.height,W.Cb=!0):1==W.Cb?(W.x=W.bc,W.y=W.cc,W.width=W.ac,W.height=W.$b,W.Cb=!1):W.width!=a||W.height!=b?(W.width=a,W.height=b):c=!1;c&&(Pc(W.width,W.height,!0),W&&W.hc&&H.get(W.hc)(W.id,W.width,W.height),W&&W.Ob&&H.get(W.Ob)(W.id,W.width,W.height))}});return 1},ka:function(){},
na:function(){},oa:function(){},ga:function(){window.removeEventListener("gamepadconnected",yd,!0);window.removeEventListener("gamepaddisconnected",Ad,!0);window.removeEventListener("keydown",Bd,!0);window.removeEventListener("keypress",wd,!0);window.removeEventListener("keyup",Cd,!0);window.removeEventListener("blur",Dd,!0);g.canvas.removeEventListener("touchmove",Ed,!0);g.canvas.removeEventListener("touchstart",Id,!0);g.canvas.removeEventListener("touchcancel",Jd,!0);g.canvas.removeEventListener("touchend",
Jd,!0);g.canvas.removeEventListener("mousemove",Ed,!0);g.canvas.removeEventListener("mousedown",Id,!0);g.canvas.removeEventListener("mouseup",Jd,!0);g.canvas.removeEventListener("wheel",Kd,!0);g.canvas.removeEventListener("mousewheel",Kd,!0);g.canvas.removeEventListener("mouseenter",Fd,!0);g.canvas.removeEventListener("mouseleave",Gd,!0);g.canvas.removeEventListener("drop",Od,!0);g.canvas.removeEventListener("dragover",Pd,!0);g.canvas.width=g.canvas.height=1;W=X=null},Y:ce,W:de,X:ee,s:fe,V:ge,Z:he,
a:wa,d:function(a){qa=a|0},L:function(a,b,c,d){return Vd(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;H=g.asm.Ca;I--;g.monitorRunDependencies&&g.monitorRunDependencies(I);0==I&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa&&(e=Qa,Qa=null,e()))}function b(e){a(e.instance)}function c(e){return Va().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){w("failed to asynchronously prepare wasm: "+f);r(f)})}var d={a:ie};I++;g.monitorRunDependencies&&g.monitorRunDependencies(I);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return w("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return ra||"function"!==typeof WebAssembly.instantiateStreaming||Sa()||Ra("file://")||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){w("wasm streaming compile failed: "+f);w("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Zd=g.___wasm_call_ctors=function(){return(Zd=g.___wasm_call_ctors=g.asm.Da).apply(null,arguments)};
g._main=function(){return(g._main=g.asm.Ea).apply(null,arguments)};
var Aa=g._malloc=function(){return(Aa=g._malloc=g.asm.Fa).apply(null,arguments)},be=g._memset=function(){return(be=g._memset=g.asm.Ga).apply(null,arguments)},Nd=g._free=function(){return(Nd=g._free=g.asm.Ha).apply(null,arguments)},$d=g.___errno_location=function(){return($d=g.___errno_location=g.asm.Ia).apply(null,arguments)},je=g.stackSave=function(){return(je=g.stackSave=g.asm.Ja).apply(null,arguments)},ke=g.stackRestore=function(){return(ke=g.stackRestore=g.asm.Ka).apply(null,arguments)},za=g.stackAlloc=
function(){return(za=g.stackAlloc=g.asm.La).apply(null,arguments)},Z=g._setThrew=function(){return(Z=g._setThrew=g.asm.Ma).apply(null,arguments)},ae=g._memalign=function(){return(ae=g._memalign=g.asm.Na).apply(null,arguments)};function he(a,b,c,d,e){var f=je();try{H.get(a)(b,c,d,e)}catch(h){ke(f);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}function ce(a,b,c){var d=je();try{return H.get(a)(b,c)}catch(e){ke(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}
function ee(a,b,c,d,e){var f=je();try{return H.get(a)(b,c,d,e)}catch(h){ke(f);if(h!==h+0&&"longjmp"!==h)throw h;Z(1,0)}}function fe(a){var b=je();try{H.get(a)()}catch(c){ke(b);if(c!==c+0&&"longjmp"!==c)throw c;Z(1,0)}}function de(a,b,c,d){var e=je();try{return H.get(a)(b,c,d)}catch(f){ke(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function ge(a,b){var c=je();try{H.get(a)(b)}catch(d){ke(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}var le;
function ma(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Qa=function me(){le||ne();le||(Qa=me)};
function ne(a){function b(){if(!le&&(le=!0,g.calledRun=!0,!xa)){g.noFSInit||Sb||(Sb=!0,Rb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Vb("stdin",g.stdin):Lb("/dev/tty","/dev/stdin"),g.stdout?Vb("stdout",null,g.stdout):Lb("/dev/tty","/dev/stdout"),g.stderr?Vb("stderr",null,g.stderr):Lb("/dev/tty1","/dev/stderr"),Mb("/dev/stdin",0),Mb("/dev/stdout",1),Mb("/dev/stderr",1));Xa(La);vb=!1;Xa(Ma);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(oe){var c=a,d=g._main;c=c||[];var e=
c.length+1,f=za(4*(e+1));A[f>>2]=Fa(ca);for(var h=1;h<e;h++)A[(f>>2)+h]=Fa(c[h-1]);A[(f>>2)+e]=0;try{var l=d(e,f);if(!noExitRuntime||0!==l){if(!noExitRuntime){if(g.onExit)g.onExit(l);xa=!0}da(l,new ma(l))}}catch(q){q instanceof ma||("unwind"==q?noExitRuntime=!0:((c=q)&&"object"===typeof q&&q.stack&&(c=[q,q.stack]),w("exception thrown: "+c),da(1,q)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Na.unshift(c);Xa(Na)}}a=a||ba;
if(!(0<I)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Oa();Xa(Ka);0<I||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=ne;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var oe=!0;g.noInitialRun&&(oe=!1);noExitRuntime=!0;ne();
